ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"1.htm	#1 Anwendungsbereich",
"2.htm	#2 Allgemeines",
"3.htm	#3 Einstufungen der Prokaryonten (Bacteria und Archaea)",
"3a.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe A",
"3b.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe B",
"3c.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe C",
"3d.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe D",
"3e.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe E",
"3f.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe F",
"3g.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe G",
"3h.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe H",
"3i.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe I",
"3j.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe J",
"3k.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe K",
"3l.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe L",
"3m.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe M",
"3n.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe N",
"3o.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe O",
"3p.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe P",
"3q.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe Q",
"3r.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe R",
"3s.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe S",
"3t.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe T",
"3u.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe U",
"3v.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe V",
"3w.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe W",
"3x.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe X",
"3y.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe Y",
"3z.htm	#3 Liste der Einstufungen der Bakterien und Archaebakterien, Gattung&nbsp;-&nbsp;Buchstabe Z",
"4.htm	#4 Literatur"
);