ord=new Array(
"titel.htm	#Titelseite",
"inhalt.htm	#Inhaltsübersicht",
"i1.htm	#§ 1 Anwendungsbereich",
"i2.htm	#§ 2 Örtliche Zuständigkeit",
"i3.htm	#§ 3 Amtshilfepflicht",
"i4.htm	#§ 4 Voraussetzungen und Grenzen der Amtshilfe",
"i5.htm	#§ 5 Auswahl der Behörde",
"i6.htm	#§ 6 Durchführung der Amtshilfe",
"i7.htm	#§ 7 Kosten der Amtshilfe",
"i8.htm	#§ 8 Begriff des Verwaltungsverfahrens",
"i9.htm	#§ 9 Nichtförmlichkeit des Verwaltungsverfahrens",
"i10.htm	#§ 10 Beteiligungsfähigkeit",
"i11.htm	#§ 11 Vornahme von Verfahrenshandlungen",
"i12.htm	#§ 12 Beteiligte",
"i13.htm	#§ 13 Bevollmächtigte und Beistände",
"i14.htm	#§ 14 Bestellung eines Empfangsbevollmächtigten",
"i15.htm	#§ 15 Bestellung eines Vertreters von Amts wegen",
"i16.htm	#§ 16 Ausgeschlossene Personen",
"i17.htm	#§ 17 Besorgnis der Befangenheit",
"i18.htm	#§ 18 Beginn des Verfahrens",
"i19.htm	#§ 19 Amtssprache",
"i20.htm	#§ 20 Untersuchungsgrundsatz",
"i21.htm	#§ 21 Beweismittel",
"i22.htm	#§ 22 Vernehmung durch das Sozial- oder Verwaltungsgericht",
"i23.htm	#§ 23 Glaubhaftmachung, Versicherung an Eides statt",
"i24.htm	#§ 24 Anhörung Beteiligter",
"i25.htm	#§ 25 Akteneinsicht durch Beteiligte",
"i26.htm	#§ 26 Fristen und Termine",
"i27.htm	#§ 27 Wiedereinsetzung in den vorigen Stand",
"i28.htm	#§ 28 Wiederholte Antragstellung",
"i29.htm	#§ 29 Beglaubigung von Dokumenten",
"i30.htm	#§ 30 Beglaubigung von Unterschriften",
"i31.htm	#§ 31 Begriff des Verwaltungsaktes",
"i31a.htm	#§ 31a Vollständig automatisierter Erlass eines Verwaltungsaktes",
"i32.htm	#§ 32 Nebenbestimmungen zum Verwaltungsakt",
"i33.htm	#§ 33 Bestimmtheit und Form des Verwaltungsaktes",
"i34.htm	#§ 34 Zusicherung",
"i35.htm	#§ 35 Begründung des Verwaltungsaktes",
"i36.htm	#§ 36 Rechtsbehelfsbelehrung",
"i37.htm	#§ 37 Bekanntgabe des Verwaltungsaktes",
"i38.htm	#§ 38 Offenbare Unrichtigkeiten im Verwaltungsakt",
"i39.htm	#§ 39 Wirksamkeit des Verwaltungsaktes",
"i40.htm	#§ 40 Nichtigkeit des Verwaltungsaktes",
"i41.htm	#§ 41 Heilung von Verfahrens-&nbsp;und Formfehlern",
"i42.htm	#§ 42 Folgen von Verfahrens-&nbsp;und Formfehlern",
"i43.htm	#§ 43 Umdeutung eines fehlerhaften Verwaltungsaktes",
"i44.htm	#§ 44 Rücknahme eines rechtswidrigen nicht begünstigenden Verwaltungsaktes",
"i45.htm	#§ 45 Rücknahme eines rechtswidrigen begünstigenden Verwaltungsaktes",
"i46.htm	#§ 46 Widerruf eines rechtmäßigen nicht begünstigenden Verwaltungsaktes",
"i47.htm	#§ 47 Widerruf eines rechtmäßigen begünstigenden Verwaltungsaktes",
"i48.htm	#§ 48 Aufhebung eines Verwaltungsaktes mit Dauerwirkung bei Änderung der Verhältnisse",
"i49.htm	#§ 49 Rücknahme und Widerruf im Rechtsbehelfsverfahren",
"i50.htm	#§ 50 Erstattung zu Unrecht erbrachter Leistungen",
"i51.htm	#§ 51 Rückgabe von Urkunden und Sachen",
"i52.htm	#§ 52 Hemmung der Verjährung durch Verwaltungsakt",
"i53.htm	#§ 53 Zulässigkeit des öffentlich-rechtlichen Vertrages",
"i54.htm	#§ 54 Vergleichsvertrag",
"i55.htm	#§ 55 Austauschvertrag",
"i56.htm	#§ 56 Schriftform",
"i57.htm	#§ 57 Zustimmung von Dritten und Behörden",
"i58.htm	#§ 58 Nichtigkeit des öffentlich-rechtlichen Vertrages",
"i59.htm	#§ 59 Anpassung und Kündigung in besonderen Fällen",
"i60.htm	#§ 60 Unterwerfung unter die sofortige Vollstreckung",
"i61.htm	#§ 61 Ergänzende Anwendung von Vorschriften",
"i62.htm	#§ 62 Rechtsbehelfe gegen Verwaltungsakte",
"i63.htm	#§ 63 Erstattung von Kosten im Vorverfahren",
"i64.htm	#§ 64 Kostenfreiheit",
"i65.htm	#§ 65 Zustellung",
"i66.htm	#§ 66 Vollstreckung",
"i67.htm	#§ 67 Begriffsbestimmungen",
"i67a.htm	#§ 67a Erhebung von Sozialdaten",
"i67b.htm	#§ 67b Speicherung, Veränderung, Nutzung, Übermittlung, Einschränkung der Verarbeitung und Löschung von Sozialdaten",
"i67c.htm	#§ 67c Zweckbindung sowie Speicherung, Veränderung und Nutzung von Sozialdaten zu anderen Zwecken",
"i67d.htm	#§ 67d Übermittlungsgrundsätze",
"i67e.htm	#§ 67e Erhebung und Übermittlung zur Bekämpfung von Leistungsmissbrauch und illegaler Ausländerbeschäftigung",
"i67f.htm	#§ 67f Erhebung und Übermittlung von Sozialdaten zur Nachweiserbringung",
"i68.htm	#§ 68 Übermittlung für Aufgaben der Polizeibehörden, der Staatsanwaltschaften, Gerichte und der Behörden der Gefahrenabwehr",
"i69.htm	#§ 69 Übermittlung für die Erfüllung sozialer Aufgaben",
"i70.htm	#§ 70 Übermittlung für die Durchführung des Arbeitsschutzes",
"i71.htm	#§ 71 Übermittlung für die Erfüllung besonderer gesetzlicher Pflichten und Mitteilungsbefugnisse",
"i72.htm	#§ 72 Übermittlung für den Schutz der inneren und äußeren Sicherheit",
"i73.htm	#§ 73 Übermittlung für die Durchführung eines Strafverfahrens",
"i74.htm	#§ 74 Übermittlung bei Verletzung der Unterhaltspflicht und beim Versorgungsausgleich",
"i74a.htm	#§ 74a Übermittlung zur Durchsetzung öffentlichrechtlicher Ansprüche und im Vollstreckungsverfahren",
"i75.htm	#§ 75 Übermittlung von Sozialdaten für die Forschung und Planung",
"i76.htm	#§ 76 Einschränkung der Übermittlungsbefugnis bei besonders schutzwürdigen Sozialdaten",
"i77.htm	#§ 77 Übermittlung ins Ausland und an internationale Organisationen",
"i77a.htm	#§ 77a Grenzüberschreitende Nachweisabrufe",
"i78.htm	#§ 78 Zweckbindung und Geheimhaltungspflicht eines Dritten, an den Daten übermittelt werden",
"i79.htm	#§ 79 Einrichtung automatisierter Verfahren auf Abruf",
"i80.htm	#§ 80 Verarbeitung von Sozialdaten im Auftrag",
"i81.htm	#§ 81 Recht auf Anrufung, Beauftragte für den Datenschutz",
"i81a.htm	#§ 81a Gerichtlicher Rechtsschutz",
"i81b.htm	#§ 81b Klagen gegen den Verantwortlichen oder Auftragsverarbeiter",
"i81b.htm	#§ 81b Klagen gegen den Verantwortlichen oder Auftragsverarbeiter",
"i81c.htm	#§ 81c Antrag auf gerichtliche Entscheidung bei angenommener Europarechtswidrigkeit eines Angemessenheitsbeschlusses der Europäischen Kommission",
"i82.htm	#§ 82 Informationspflichten bei der Erhebung von Sozialdaten bei der betroffenen Person",
"i82a.htm	#§ 82a Informationspflichten, wenn Sozialdaten nicht bei der betroffenen Person erhoben wurden",
"i83.htm	#§ 83 Auskunftsrecht der betroffenen Personen",
"i83a.htm	#§ 83a Benachrichtigung bei einer Verletzung des Schutzes von Sozialdaten",
"i84.htm	#§ 84 Recht auf Berichtigung, Löschung, Einschränkung der Verarbeitung und Widerspruch",
"i85.htm	#§ 85 Strafvorschriften",
"i85a.htm	#§ 85a Bußgeldvorschriften",
"i86.htm	#§ 86 Zusammenarbeit",
"i87.htm	#§ 87 Beschleunigung der Zusammenarbeit",
"i88.htm	#§ 88 Auftrag",
"i89.htm	#§ 89 Ausführung des Auftrags",
"i90.htm	#§ 90 Anträge und Widerspruch beim Auftrag",
"i91.htm	#§ 91 Erstattung von Aufwendungen",
"i92.htm	#§ 92 Kündigung des Auftrags",
"i93.htm	#§ 93 Gesetzlicher Auftrag",
"i94.htm	#§ 94 Arbeitsgemeinschaften",
"i95.htm	#§ 95 Zusammenarbeit bei Planung und Forschung",
"i96.htm	#§ 96 Ärztliche Untersuchungen, psychologische Eignungsuntersuchungen",
"i97.htm	#§ 97 Durchführung von Aufgaben durch Dritte",
"i98.htm	#§ 98 Auskunftspflicht des Arbeitgebers",
"i99.htm	#§ 99 Auskunftspflicht von Angehörigen, Unterhaltspflichtigen oder sonstigen Personen",
"i100.htm	#§ 100 Auskunftspflicht des Arztes oder Angehörigen eines anderen Heilberufs",
"i101.htm	#§ 101 Auskunftspflicht der Leistungsträger",
"i101a.htm	#§ 101a Mitteilungen der Meldebehörden",
"i102.htm	#§ 102 Anspruch des vorläufig leistenden Leistungsträgers",
"i103.htm	#§ 103 Anspruch des Leistungsträgers, dessen Leistungsverpflichtung nachträglich entfallen ist",
"i104.htm	#§ 104 Anspruch des nachrangig verpflichteten Leistungsträgers",
"i105.htm	#§ 105 Anspruch des unzuständigen Leistungsträgers",
"i106.htm	#§ 106 Rangfolge bei mehreren Erstattungsberechtigten",
"i107.htm	#§ 107 Erfüllung",
"i108.htm	#§ 108 Erstattung in Geld, Verzinsung",
"i109.htm	#§ 109 Verwaltungskosten und Auslagen",
"i110.htm	#§ 110 Pauschalierung",
"i111.htm	#§ 111 Ausschlussfrist",
"i112.htm	#§ 112 Rückerstattung",
"i113.htm	#§ 113 Verjährung",
"i114.htm	#§ 114 Rechtsweg",
"i115.htm	#§ 115 Ansprüche gegen den Arbeitgeber",
"i116.htm	#§ 116 Ansprüche gegen Schadenersatzpflichtige",
"i117.htm	#§ 117 Schadenersatzansprüche mehrerer Leistungsträger",
"i118.htm	#§ 118 Bindung der Gerichte",
"i119.htm	#§ 119 Übergang von Beitragsansprüchen",
"i120.htm	#§ 120 Übergangsregelung",
"a_01.htm	#Anlage"
);