ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhaltsverzeichnis",
"vor.htm	#Vorbemerkung",
"1.htm	#1 Anwendungsbereich",
"2.htm	#2 Begriffsbestimmungen und Erläuterungen",
"3.htm	#3 Grundpflichten des Arbeitgebers",
"4.htm	#4 Gefährdungsbeurteilung",
"4_1.htm	#4.1 Mögliche Gefährdungen",
"4_2.htm	#4.2 Beurteilung",
"5.htm	#5 Unterweisung und Mitwirkung der Beschäftigten",
"6.htm	#6 Arbeitsorganisation",
"7.htm	#7 Vorsorge bei Tätigkeiten an Bildschirmgeräten",
"8_1.htm	#8.1 Allgemeine Anforderungen an Bildschirmarbeitsplätze",
"8_2.htm	#8.2 Bildschirm, Tastatur und sonstige Eingabemittel",
"8_2_2.htm	#8.2.2 Tastatur",
"8_2_3.htm	#8.2.3 Maus",
"8_3.htm	#8.3 Sonstige Arbeitsmittel",
"8_3_1.htm	#8.3.1 Arbeitstisch/Arbeitsfläche",
"8_3_2.htm	#8.3.2 Büroarbeitsstuhl",
"8_3_3.htm	#8.3.3 Vorlagenhalter und Fußstütze",
"8_3_4.htm	#8.3.4 Schränke, Bürocontainer, Raumgliederungselemente",
"8_3_5.htm	#8.3.5 Elektrische Installation in Büromöbeln",
"8_3_6.htm	#8.3.6 Büromaschinen und Bürogeräte",
"8_3_7.htm	#8.3.7 Drucker",
"8_4_1.htm	#8.4.1 Platzbedarf",
"8_4_2.htm	#8.4.2 Beleuchtung",
"8_4_3.htm	#8.4.3 Lärm",
"8_4_4.htm	#8.4.4 Raumklima",
"8_4_5.htm	#8.4.5 Strahlung",
"8_5.htm	#8.5 Zusammenwirken Mensch – Arbeitsmittel (Softwareergonomie)",
"9.htm	#9  Telearbeitsplätze und mobiles Arbeiten"
);