ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Errichtung von Betriebsräten",
"2.htm	#§ 2 Stellung der Gewerkschaften und Vereinigungen der Arbeitgeber",
"3.htm	#§ 3 Abweichende Regelungen",
"4.htm	#§ 4 Betriebsteile, Kleinstbetriebe",
"5.htm	#§ 5 Arbeitnehmer",
"6.htm	#§ 6 (weggefallen)",
"7.htm	#§ 7 Wahlberechtigung",
"8.htm	#§ 8 Wählbarkeit",
"9.htm	#§ 9 Zahl der Betriebsratsmitglieder",
"10.htm	#§ 10 (weggefallen)",
"11.htm	#§ 11 Ermäßigte Zahl der Betriebsratsmitglieder",
"12.htm	#§ 12 Abweichende Verteilung der Betriebsratssitze",
"13.htm	#§ 13 Zeitpunkt der Betriebsratswahlen",
"14.htm	#§ 14 Wahlvorschriften",
"14a.htm	#§ 14a Vereinfachtes Wahlverfahren für Kleinbetriebe",
"15.htm	#§ 15 Zusammensetzung nach Beschäftigungsarten und Geschlechter",
"16.htm	#§ 16 Bestellung des Wahlvorstands",
"17.htm	#§ 17 Bestellung des Wahlvorstands in Betrieben ohne Betriebsrat",
"17a.htm	#§ 17a Bestellung des Wahlvorstands im vereinfachten Wahlverfahren",
"18.htm	#§ 18 Vorbereitung und Durchführung der Wahl",
"18a.htm	#§ 18a Zuordnung der leitenden Angestellten bei Wahlen",
"19.htm	#§ 19 Wahlanfechtung",
"20.htm	#§ 20 Wahlschutz und Wahlkosten",
"21.htm	#§ 21 Amtszeit",
"21a.htm	#§ 21a Übergangsmandat",
"21b.htm	#§ 21b Restmandat",
"22.htm	#§ 22 Weiterführung der Geschäfte des Betriebsrats",
"23.htm	#§ 23 Verletzung gesetzlicher Pflichten",
"24.htm	#§ 24 Erlöschen der Mitgliedschaft",
"25.htm	#§ 25 Ersatzmitglieder",
"26.htm	#§ 26 Vorsitzender",
"27.htm	#§ 27 Betriebsausschuss",
"28.htm	#§ 28 Übertragung von Aufgaben auf Ausschüsse",
"28a.htm	#§ 28a Übertragung von Aufgaben auf Arbeitsgruppen",
"29.htm	#§ 29 Einberufung der Sitzungen",
"30.htm	#§ 30 Betriebsratssitzungen",
"31.htm	#§ 31 Teilnahme der Gewerkschaften",
"32.htm	#§ 32 Teilnahme der Schwerbehindertenvertretung",
"33.htm	#§ 33 Beschlüsse des Betriebsrats",
"34.htm	#§ 34 Sitzungsniederschrift",
"35.htm	#§ 35 Aussetzung von Beschlüssen",
"36.htm	#§ 36 Geschäftsordnung",
"37.htm	#§ 37 Ehrenamtliche Tätigkeit, Arbeitsversäumnis",
"38.htm	#§ 38 Freistellungen",
"39.htm	#§ 39 Sprechstunden",
"40.htm	#§ 40 Kosten und Sachaufwand des Betriebsrats",
"41.htm	#§ 41 Umlageverbot",
"42.htm	#§ 42 Zusammensetzung, Teilversammlung, Abteilungsversammlung",
"43.htm	#§ 43 Regelmäßige Betriebs-&nbsp;und Abteilungsversammlungen",
"44.htm	#§ 44 Zeitpunkt und Verdienstausfall",
"45.htm	#§ 45 Themen der Betriebs-&nbsp;und Abteilungsversammlungen",
"46.htm	#§ 46 Beauftragte der Verbände",
"47.htm	#§ 47 Voraussetzungen der Errichtung, Mitgliederzahl, Stimmengewicht",
"48.htm	#§ 48 Ausschluss von Gesamtbetriebsratsmitgliedern",
"49.htm	#§ 49 Erlöschen der Mitgliedschaft",
"50.htm	#§ 50 Zuständigkeit",
"51.htm	#§ 51 Geschäftsführung",
"52.htm	#§ 52 Teilnahme der Gesamtschwerbehinderten-vertretung",
"53.htm	#§ 53 Betriebsräteversammlung",
"54.htm	#§ 54 Errichtung des Konzernbetriebsrats",
"55.htm	#§ 55 Zusammensetzung des Konzernbetriebsrats, Stimmengewicht",
"56.htm	#§ 56 Ausschluss von Konzernbetriebsratsmitgliedern",
"57.htm	#§ 57 Erlöschen der Mitgliedschaft",
"58.htm	#§ 58 Zuständigkeit",
"59.htm	#§ 59 Geschäftsführung",
"59a.htm	#§ 59a Teilnahme der Konzernschwerbehinderten-vertretung",
"60.htm	#§ 60 Errichtung und Aufgabe",
"61.htm	#§ 61 Wahlberechtigung und Wählbarkeit",
"62.htm	#§ 62 Zahl der Jugend-&nbsp;und Auszubildendenvertreter, Zusammensetzung der Jugend-&nbsp;und Auszubildendenvertretung",
"63.htm	#§ 63 Wahlvorschriften",
"64.htm	#§ 64 Zeitpunkt der Wahlen und Amtszeit",
"65.htm	#§ 65 Geschäftsführung",
"66.htm	#§ 66 Aussetzung von Beschlüssen des Betriebsrats",
"67.htm	#§ 67 Teilnahme an Betriebsratssitzungen",
"68.htm	#§ 68 Teilnahme an gemeinsamen Besprechungen",
"69.htm	#§ 69 Sprechstunden",
"70.htm	#§ 70 Allgemeine Aufgaben",
"71.htm	#§ 71 Jugend- und Auszubildendenversammlung",
"72.htm	#§ 72 Voraussetzungen der Errichtung, Mitgliederzahl, Stimmengewicht",
"73.htm	#§ 73 Geschäftsführung und Geltung sonstiger Vorschriften",
"73a.htm	#§ 73a Voraussetzung der Errichtung, Mitgliederzahl, Stimmengewicht",
"73b.htm	#§ 73b Geschäftsführung und Geltung sonstiger Vorschriften",
"74.htm	#§ 74 Grundsätze für die Zusammenarbeit",
"75.htm	#§ 75 Grundsätze für die Behandlung der Betriebsangehörigen",
"76.htm	#§ 76 Einigungsstelle",
"76a.htm	#§ 76a Kosten der Einigungsstelle",
"77.htm	#§ 77 Durchführung gemeinsamer Beschlüsse, Betriebsvereinbarungen",
"78.htm	#§ 78 Schutzbestimmungen",
"78a.htm	#§ 78a Schutz Auszubildender in besonderen Fällen",
"79.htm	#§ 79 Geheimhaltungspflicht",
"79a.htm	#§ 79a Datenschutz",
"80.htm	#§ 80 Allgemeine Aufgaben",
"81.htm	#§ 81 Unterrichtungs- und Erörterungspflicht des Arbeitgebers",
"82.htm	#§ 82 Anhörungs- und Erörterungsrecht des Arbeitnehmers",
"83.htm	#§ 83 Einsicht in die Personalakten",
"84.htm	#§ 84 Beschwerderecht",
"85.htm	#§ 85 Behandlung von Beschwerden durch den Betriebsrat",
"86.htm	#§ 86 Ergänzende Vereinbarungen",
"86a.htm	#§ 86a Vorschlagsrecht der Arbeitnehmer",
"87.htm	#§ 87 Mitbestimmungsrechte",
"88.htm	#§ 88 Freiwillige Betriebsvereinbarungen",
"89.htm	#§ 89 Arbeits-&nbsp;und betrieblicher Umweltschutz",
"90.htm	#§ 90 Unterrichtungs- und Beratungsrechte",
"91.htm	#§ 91 Mitbestimmungsrecht",
"92.htm	#§ 92 Personalplanung",
"92a.htm	#§ 92a Beschäftigungssicherung",
"93.htm	#§ 93 Ausschreibung von Arbeitsplätzen",
"94.htm	#§ 94 Personalfragebogen, Beurteilungsgrundsätze",
"95.htm	#§ 95 Auswahlrichtlinien",
"96.htm	#§ 96 Förderung der Berufsbildung",
"97.htm	#§ 97 Einrichtungen und Maßnahmen der Berufsbildung",
"98.htm	#§ 98 Durchführung betrieblicher Bildungsmaßnahmen",
"99.htm	#§ 99 Mitbestimmung bei personellen Einzelmaßnahmen",
"100.htm	#§ 100 Vorläufige personelle Maßnahmen",
"101.htm	#§ 101 Zwangsgeld",
"102.htm	#§ 102 Mitbestimmung bei Kündigungen",
"103.htm	#§ 103 Außerordentliche Kündigung und Versetzung in besonderen Fällen",
"104.htm	#§ 104 Entfernung betriebsstörender Arbeitnehmer",
"105.htm	#§ 105 Leitende Angestellte",
"106.htm	#§ 106 Wirtschaftsausschuss",
"107.htm	#§ 107 Bestellung und Zusammensetzung des Wirtschaftsausschusses",
"108.htm	#§ 108 Sitzungen",
"109.htm	#§ 109 Beilegung von Meinungsverschiedenheite",
"109a.htm	#§ 109a Unternehmensübernahme",
"110.htm	#§ 110 Unterrichtung der Arbeitnehmer",
"111.htm	#§ 111 Betriebsänderungen",
"112.htm	#§ 112 Interessenausgleich über die Betriebsänderung, Sozialplan",
"112a.htm	#§ 112a Erzwingbarer Sozialplan bei Personalabbau, Neugründungen",
"113.htm	#§ 113 Nachteilsausgleich",
"114.htm	#§ 114 Grundsätze",
"115.htm	#§ 115 Bordvertretung",
"116.htm	#§ 116 Seebetriebsrat",
"117.htm	#§ 117 Geltung für die Luftfahrt",
"118.htm	#§ 118 Geltung für Tendenzbetriebe und Religionsgemeinschaften",
"119.htm	#§ 119 Straftaten gegen Betriebsverfassungsorgane und ihre Mitglieder",
"120.htm	#§ 120 Verletzung von Geheimnissen",
"121.htm	#§ 121 Bußgeldvorschriften",
"122.htm	#§ 122 (Änderung des Bürgerlichen Gesetzbuchs)",
"123.htm	#§ 123 (Änderung des Kündigungsschutzgesetzes)",
"124.htm	#§ 124 (Änderung des Arbeitsgerichtsgesetzes)",
"125.htm	#§ 125 Erstmalige Wahlen nach diesem Gesetz",
"126.htm	#§ 126 Ermächtigung zum Erlass von Wahlordnungen",
"127.htm	#§ 127 Verweisungen",
"128.htm	#§ 128 Bestehende abweichende Tarifverträge",
"129.htm	#§ 129 Sonderregelungen aus Anlass der COVID-19-Pandemie",
"130.htm	#§ 130 Öffentlicher Dienst",
"131.htm	#§ 131 Berlin-Klausel",
"132.htm	#§ 132 (Inkrafttreten)"
);