ord=new Array(
"titel.htm	#Titelseite",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Begriffsbestimmungen",
"2.htm	#§ 2 Nicht gerechtfertigte Tätigkeitsarten",
"3.htm	#§ 3 Verfahren zur Prüfung der Rechtfertigung von Tätigkeitsarten nach § 7 des Strahlenschutzgesetzes",
"4.htm	#§ 4 Verfahren zur Prüfung der Rechtfertigung von Tätigkeitsarten nach § 38 des Strahlenschutzgesetzes",
"5.htm	#§ 5 Genehmigungsfreier Umgang",
"5a.htm	#§ 5a Genehmigungsfreier Zusatz radioaktiver Stoffe",
"6.htm	#§ 6 Genehmigungsfreier Besitz von Kernbrennstoffen",
"7.htm	#§ 7 Genehmigungs- und anzeigefreier Betrieb von Anlagen zur Erzeugung ionisierender Strahlung",
"8.htm	#§ 8 Genehmigungsfreier Betrieb von Störstrahlern",
"9.htm	#§ 9 Anzeigefreie Prüfung, Erprobung, Wartung und Instandsetzung von Röntgeneinrichtungen oder Störstrahlern",
"10.htm	#§ 10 Befreiung von der Pflicht zur Deckungsvorsorge",
"11.htm	#§ 11 Freigrenzen",
"12.htm	#§ 12 Genehmigungsbedürftige grenzüberschreitende Verbringung",
"13.htm	#§ 13 Anmeldebedürftige grenzüberschreitende Verbringung",
"14.htm	#§ 14 Ausnahmen; andere Vorschriften über die grenzüberschreitende Verbringung",
"15.htm	#§ 15 Voraussetzungen für die Erteilung der Genehmigung für die grenzüberschreitende Verbringung",
"16.htm	#§ 16 Technische Anforderungen an die Bauartzulassung einer Vorrichtung, die sonstige radioaktive Stoffe enthält",
"17.htm	#§ 17 Technische Anforderungen an die Bauartzulassung von Störstrahlern",
"18.htm	#§ 18 Technische Anforderungen an die Bauartzulassung von Röntgenstrahlern",
"19.htm	#§ 19 Technische Anforderungen an die Bauartzulassung von Basisschutzgeräten",
"20.htm	#§ 20 Technische Anforderungen an die Bauartzulassung von Hochschutzgeräten",
"21.htm	#§ 21 Technische Anforderungen an die Bauartzulassung von Vollschutzgeräten",
"22.htm	#§ 22 Technische Anforderungen an die Bauartzulassung von Schulröntgeneinrichtungen",
"23.htm	#§ 23 Technische Anforderungen an die Bauartzulassung einer Anlage zur Erzeugung ionisierender Strahlung als Vollschutzanlage",
"24.htm	#§ 24 Pflichten des Inhabers einer Bauartzulassung",
"25.htm	#§ 25 Pflichten des Inhabers einer bauartzugelassenen Vorrichtung",
"26.htm	#§ 26 Bekanntmachung",
"27.htm	#§ 27 Bestimmung der Überwachungsbedürftigkeit von Rückständen",
"28.htm	#§ 28 Ermittlung der von Rückständen verursachten Expositionen",
"29.htm	#§ 29 Entlassung überwachungsbedürftiger Rückstände aus der Überwachung zur Verwertung oder Beseitigung nach dem Kreislaufwirtschaftsgesetz",
"30.htm	#§ 30 Entlassung überwachungsbedürftiger Rückstände aus der Überwachung zur Verwertung als Bauprodukt",
"31.htm	#§ 31 Freigabe radioaktiver Stoffe; Dosiskriterium",
"32.htm	#§ 32 Antrag auf Freigabe",
"33.htm	#§ 33 Erteilung der Freigabe",
"34.htm	#§ 34 Vermischungsverbot",
"35.htm	#§ 35 Uneingeschränkte Freigabe",
"36.htm	#§ 36 Spezifische Freigabe",
"37.htm	#§ 37 Freigabe im Einzelfall",
"38.htm	#§ 38 Freigabe von Amts wegen",
"39.htm	#§ 39 Einvernehmen bei der spezifischen Freigabe zur Beseitigung und bei der spezifischen Freigabe von Metallschrott zum Recycling",
"40.htm	#§ 40 Abfallrechtlicher Verwertungs- und Beseitigungsweg",
"41.htm	#§ 41 Festlegung des Verfahrens",
"42.htm	#§ 42 Pflichten des Inhabers einer Freigabe",
"43.htm	#§ 43 Pflichten des Strahlenschutzbeauftragten",
"44.htm	#§ 44 Pflichten bei Nutzung durch weitere Strahlenschutzverantwortliche",
"45.htm	#§ 45 Strahlenschutzanweisung",
"46.htm	#§ 46 Bereithalten des Strahlenschutzgesetzes und der Strahlenschutzverordnung",
"47.htm	#§ 47 Erforderliche Fachkunde im Strahlenschutz",
"48.htm	#§ 48 Aktualisierung der Fachkunde",
"49.htm	#§ 49 Erforderliche Kenntnisse im Strahlenschutz bei der Anwendung am Menschen und am Tier in der Tierheilkunde",
"50.htm	#§ 50 Widerruf der Anerkennung der erforderlichen Fachkunde oder der erforderlichen Kenntnisse",
"51.htm	#§ 51 Anerkennung von Kursen",
"52.htm	#§ 52 Einrichten von Strahlenschutzbereichen",
"53.htm	#§ 53 Abgrenzung, Kennzeichnung und Sicherung von Strahlenschutzbereichen",
"54.htm	#§ 54 Vorbereitung der Brandbekämpfung",
"55.htm	#§ 55 Zutritt zu Strahlenschutzbereichen",
"56.htm	#§ 56 Messtechnische Überwachung in Strahlenschutzbereichen",
"57.htm	#§ 57 Kontamination und Dekontamination",
"58.htm	#§ 58 Verlassen von und Herausbringen aus Strahlenschutzbereichen",
"59.htm	#§ 59 Einrichten von Strahlenschutzbereichen bei Tätigkeiten mit natürlich vorkommenden radioaktiven Stoffen",
"60.htm	#§ 60 Röntgenräume",
"61.htm	#§ 61 Bestrahlungsräume",
"62.htm	#§ 62 Räume für den Betrieb von Störstrahlern",
"63.htm	#§ 63 Unterweisung",
"64.htm	#§ 64 Pflicht zur Ermittlung der Körperdosis; zu überwachende Personen",
"65.htm	#§ 65 Vorgehen bei der Ermittlung der Körperdosis",
"66.htm	#§ 66 Messung der Personendosis",
"67.htm	#§ 67 Ermittlung der Körperdosis des fliegenden Personals",
"68.htm	#§ 68 Beschäftigung mit Strahlenpass",
"69.htm	#§ 69 Schutz von schwangeren und stillenden Personen",
"70.htm	#§ 70 Schutz beim Umgang mit offenen radioaktiven Stoffen; Beschäftigungsverbote",
"71.htm	#§ 71 Kategorien beruflich exponierter Personen",
"72.htm	#§ 72 Dosisrichtwerte bei Tätigkeiten",
"73.htm	#§ 73 Dosisbegrenzung bei Überschreitung von Grenzwerten",
"74.htm	#§ 74 Besonders zugelassene Expositionen",
"75.htm	#§ 75 Sonstige Schutzvorkehrungen",
"76.htm	#§ 76 Besondere Regelungen zum Schutz des raumfahrenden Personals",
"77.htm	#§ 77 Ärztliche Überwachung beruflich exponierter Personen",
"78.htm	#§ 78 Ärztliche Überwachung nach Beendigung der Aufgabenwahrnehmung",
"79.htm	#§ 79 Ärztliche Bescheinigung",
"80.htm	#§ 80 Behördliche Entscheidung",
"81.htm	#§ 81 Besondere ärztliche Überwachung",
"82.htm	#§ 82 Strahlenschutz in Schulen und bei Lehr- und Ausbildungsverhältnissen",
"83.htm	#§ 83 Werte für hochradioaktive Strahlenquellen",
"84.htm	#§ 84 Register über hochradioaktive Strahlenquellen",
"85.htm	#§ 85 Buchführung und Mitteilung",
"86.htm	#§ 86 Buchführung und Mitteilung bei der Freigabe",
"87.htm	#§ 87 Sicherung und Lagerung radioaktiver Stoffe",
"88.htm	#§ 88 Wartung und Prüfung",
"89.htm	#§ 89 Dichtheitsprüfung",
"90.htm	#§ 90 Strahlungsmessgeräte",
"91.htm	#§ 91 Kennzeichnungspflicht",
"92.htm	#§ 92 Besondere Kennzeichnungspflichten",
"93.htm	#§ 93 Entfernen von Kennzeichnungen",
"94.htm	#§ 94 Abgabe radioaktiver Stoffe",
"95.htm	#§ 95 Rücknahme hochradioaktiver Strahlenquellen",
"96.htm	#§ 96 Überlassen von Störstrahlern",
"97.htm	#§ 97 Aufbewahrung und Bereithalten von Unterlagen",
"98.htm	#§ 98 Einweisung in Tätigkeiten mit Strahlungsquellen",
"99.htm	#§ 99 Begrenzung der Ableitung radioaktiver Stoffe",
"100.htm	#§ 100 Ermittlung der für Einzelpersonen der Bevölkerung zu erwartenden Exposition",
"101.htm	#§ 101 Ermittlung der von Einzelpersonen der Bevölkerung erhaltenen Exposition",
"102.htm	#§ 102 Zulässige Ableitungen radioaktiver Stoffe",
"103.htm	#§ 103 Emissions- und Immissionsüberwachung",
"104.htm	#§ 104 Begrenzung der Exposition durch Störfälle",
"105.htm	#§ 105 Vorbereitende Maßnahmen zur Vermeidung, zum Erkennen und zur Eindämmung der Auswirkungen eines Vorkommnisses bei der Anwendung am Menschen",
"106.htm	#§ 106 Vorbereitende Maßnahmen für Notfälle oder Störfälle",
"107.htm	#§ 107 Maßnahmen bei einem Notfall oder Störfall",
"108.htm	#§ 108 Meldung eines bedeutsamen Vorkommnisses",
"109.htm	#§ 109 Untersuchung, Aufzeichnung und Aufbewahrung",
"110.htm	#§ 110 Aufgaben der zuständigen Aufsichtsbehörden",
"111.htm	#§ 111 Aufgaben der zentralen Stelle",
"112.htm	#§ 112 Meldung und Erfassung von Vorkommnissen nach anderen Rechtsvorschriften",
"113.htm	#§ 113 Ausnahme",
"114.htm	#§ 114 Anforderungen an die Ausrüstung bei der Anwendung am Menschen",
"115.htm	#§ 115 Qualitätssicherung vor Inbetriebnahme; Abnahmeprüfung; Bezugswertfestlegung",
"116.htm	#§ 116 Konstanzprüfung",
"117.htm	#§ 117 Aufzeichnungen",
"118.htm	#§ 118 Bestandsverzeichnis",
"119.htm	#§ 119 Rechtfertigende Indikation",
"120.htm	#§ 120 Schutz von besonderen Personengruppen",
"121.htm	#§ 121 Maßnahmen bei der Anwendung",
"122.htm	#§ 122 Beschränkung der Exposition",
"123.htm	#§ 123 Anforderungen im Zusammenhang mit dem Betrieb einer Röntgeneinrichtung zur Teleradiologie",
"124.htm	#§ 124 Informationspflichten",
"125.htm	#§ 125 Diagnostische Referenzwerte; Bevölkerungsdosis",
"126.htm	#§ 126 Risikobeurteilung vor Strahlenbehandlungen",
"127.htm	#§ 127 Aufbewahrung, Weitergabe und Übermittlung von Aufzeichnungen, Röntgenbildern, digitalen Bilddaten und sonstigen Untersuchungsdaten",
"128.htm	#§ 128 Bestimmung von ärztlichen und zahnärztlichen Stellen zur Qualitätssicherung",
"129.htm	#§ 129 Mitteilung der Aufnahme und Beendigung einer Tätigkeit an eine ärztliche oder zahnärztliche Stelle",
"130.htm	#§ 130 Maßnahmen zur Qualitätssicherung durch ärztliche und zahnärztliche Stellen",
"131.htm	#§ 131 Medizinphysik-Experte",
"132.htm	#§ 132 Aufgaben des Medizinphysik-Experten",
"133.htm	#§ 133 Grundsatz der Einwilligung nach Aufklärung und Befragung",
"134.htm	#§ 134 Einwilligungen der in das Forschungsvorhaben eingeschlossenen Person",
"135.htm	#§ 135 Aufklärung und Befragung",
"136.htm	#§ 136 Anwendung an nicht Einwilligungsfähigen und an Minderjährigen",
"137.htm	#§ 137 Weitere Anwendungsverbote und Anwendungsbeschränkungen",
"138.htm	#§ 138 Besondere Schutzpflichten",
"139.htm	#§ 139 Qualitätssicherung",
"140.htm	#§ 140 Aufbewahrungspflichten; weitere Regelungen zu Aufzeichnungen",
"141.htm	#§ 141 Mitteilungspflichten",
"142.htm	#§ 142 Abschlussbericht",
"143.htm	#§ 143 Behördliche Schutzanordnung",
"144.htm	#§ 144 Anforderungen im Zusammenhang mit der Anwendung",
"145.htm	#§ 145 Berechtigte Personen bei der Anwendung am Menschen",
"146.htm	#§ 146 Berechtigte Personen in der Tierheilkunde",
"147.htm	#§ 147 Berechtigte Personen außerhalb der Anwendung am Menschen oder der Tierheilkunde",
"148.htm	#§ 148 Informationspflichten des Herstellers von Geräten",
"149.htm	#§ 149 Aufsichtsprogramm",
"150.htm	#§ 150 Dosimetrie bei Einsatzkräften",
"151.htm	#§ 151 Besondere ärztliche Überwachung von Einsatzkräften",
"152.htm	#§ 152 Hilfeleistung und Beratung von Behörden, Hilfsorganisationen und Einsatzkräften bei einem Notfall",
"153.htm	#§ 153 Festlegung von Gebieten nach § 121 Absatz 1 Satz 1 des Strahlenschutzgesetzes",
"154.htm	#§ 154 Maßnahmen zum Schutz vor Radon für Neubauten in Gebieten nach § 121 Absatz 1 Satz 1 des Strahlenschutzgesetzes",
"155.htm	#§ 155 Messung der Radon-222-Aktivitätskonzentration; anerkannte Stelle",
"156.htm	#§ 156 Arbeitsplatzbezogene Abschätzung der Exposition",
"157.htm	#§ 157 Ermittlung der Exposition und der Körperdosis",
"158.htm	#§ 158 Weitere Anforderungen des beruflichen Strahlenschutzes",
"159.htm	#§ 159 Ermittlung der spezifischen Aktivität",
"160.htm	#§ 160 Ermittlung der Exposition",
"161.htm	#§ 161 Prüfwerte bei radioaktiven Altlasten und bei der Stilllegung und Sanierung der Betriebsanlagen und Betriebsstätten des Uranerzbergbaus",
"162.htm	#§ 162 Emissions- und Immissionsüberwachung bei der Stilllegung und Sanierung der Betriebsanlagen und Betriebsstätten des Uranerzbergbaus",
"163.htm	#§ 163 Grundsätze für die Optimierung von Sanierungsmaßnahmen",
"164.htm	#§ 164 Inhalt von Sanierungsplänen",
"165.htm	#§ 165 Schutz der Arbeitskräfte bei radioaktiven Altlasten",
"166.htm	#§ 166 Schutz der Arbeitskräfte bei sonstigen bestehenden Expositionssituationen",
"167.htm	#§ 167 Abhandenkommen",
"168.htm	#§ 168 Fund und Erlangung",
"169.htm	#§ 169 Kontaminiertes Metall",
"170.htm	#§ 170 Information des zuständigen Bundesministeriums",
"171.htm	#§ 171 Dosis- und Messgrößen",
"172.htm	#§ 172 Messstellen",
"173.htm	#§ 173 Strahlenschutzregister",
"174.htm	#§ 174 Strahlenpass",
"175.htm	#§ 175 Ermächtigte Ärzte",
"176.htm	#§ 176 Duldungspflichten",
"177.htm	#§ 177 Bestimmung von Sachverständigen",
"178.htm	#§ 178 Erweiterung der Bestimmung",
"179.htm	#§ 179 Überprüfung der Zuverlässigkeit",
"180.htm	#§ 180 Unabhängigkeit",
"181.htm	#§ 181 Fachliche Qualifikation",
"182.htm	#§ 182 Prüfmaßstab",
"183.htm	#§ 183 Pflichten des behördlich bestimmten Sachverständigen",
"184.htm	#§ 184 Ordnungswidrigkeiten",
"185.htm	#§ 185 Bauartzulassung (§§ 16 bis 26)",
"186.htm	#§ 186 Rückstände (§ 29)",
"187.htm	#§ 187 Freigabe (§§ 31 bis 42)",
"188.htm	#§ 188 Betriebliche Organisation des Strahlenschutzes (§§ 44 und 45)",
"189.htm	#§ 189 Erforderliche Fachkunde und Kenntnisse im Strahlenschutz (§§ 47, 49 und 51)",
"190.htm	#§ 190 Übergangsvorschriften im Zusammenhang mit Strahlenschutzbereichen (§§ 52 bis 62)",
"191.htm	#§ 191 Dosisrichtwerte bei Tätigkeiten (§ 72)",
"192.htm	#§ 192 Register über hochradioaktive Strahlenquellen (§ 84)",
"193.htm	#§ 193 Ermittlung der für Einzelpersonen der Bevölkerung zu erwartenden und erhaltenen Exposition (§§ 99, 100, 101, Anlage 11)",
"194.htm	#§ 194 Begrenzung der Exposition durch Störfälle (§ 104)",
"195.htm	#§ 195 Ausrüstung bei der Anwendung am Menschen (§ 114)",
"196.htm	#§ 196 Ärztliche und zahnärztliche Stellen (§ 128)",
"197.htm	#§ 197 Dosis- und Messgrößen (§ 171, Anlage 18)",
"198.htm	#§ 198 Strahlenpass (§ 174)",
"199.htm	#§ 199 Ermächtigte Ärzte (§ 175)",
"200.htm	#§ 200 Behördlich bestimmte Sachverständige (§ 181)",
"anl1.htm	#Anlage 1  Liste der nicht gerechtfertigten Tätigkeitsarten ",
"anl2.htm	#Anlage 2 Erforderliche Unterlagen zur Prüfung der Rechtfertigung von Tätigkeitsarten",
"anl3.htm	#Anlage 3 Genehmigungsfreie Tätigkeiten",
"anl4.htm	#Anlage 4 Freigrenzen, Freigabewerte für verschiedene Freigabearten, Werte für hochradioaktive Strahlenquellen, Werte der Oberflächenkontamination, Liste der Radionuklide und bei den Berechnungen berücksichtigte Tochternuklide",
"anl5.htm	#Anlage 5 Überwachungsgrenzen sowie Verwertungs- und Beseitigungswege für die Bestimmung der Überwachungsbedürftigkeit von Rückständen",
"anl6.htm	#Anlage 6 Grundsätze für die Ermittlung von Expositionen bei Rückständen ",
"anl7.htm	#Anlage 7 Voraussetzungen für die Entlassung aus der Überwachung bei gemeinsamer Deponierung von überwachungsbedürftigen Rückständen mit anderen Rückständen und Abfällen",
"anl8.htm	#Anlage 8 Festlegungen zur Freigabe",
"anl9.htm	#Anlage 9 Liste der Daten über hochradioaktive Strahlenquellen (HRQ), die im Register über hochradioaktive Strahlenquellen (HRQ-Register) erfasst werden",
"anl10.htm	#Anlage 10 Strahlenzeichen",
"anl11.htm	#Anlage 11 Annahmen bei der Berechnung der Exposition",
"anl12.htm	#Anlage 12 Leitstellen des Bundes für die Emissions- und Immissionsüberwachung",
"anl13.htm	#Anlage 13 Information der Bevölkerung zur Vorbereitung auf einen Notfall",
"anl14.htm	#Anlage 14 Kriterien für die Bedeutsamkeit eines Vorkommnisses bei medizinischer Exposition und bei Exposition der untersuchten Person bei einer nichtmedizinischen Anwendung",
"anl15.htm	#Anlage 15 Kriterien für die Bedeutsamkeit eines Vorkommnisses in einer geplanten Expositionssituation",
"anl16.htm	#Anlage 16  Kriterien zur Bestimmung der Art und des Ausmaßes des mit einer Tätigkeit verbundenen Risikos ",
"anl17.htm	#Anlage 17 Aktivitätsindex und nicht zu überschreitende Werte nach § 135 Absatz 1 Satz 3 des Strahlenschutzgesetzes",
"anl18.htm	#Anlage 18 Dosis- und Messgrößen",
"anl19.htm	#Anlage 19  Prüfungen zum Erwerb und Erhalt der erforderlichen fachlichen Qualifikation für die Ausübung einer Tätigkeit als behördlich bestimmter Sachverständiger nach § 172 Absatz 1 des Strahlenschutzgesetzes"
);