ord=new Array(
"titel.htm		#Titel",
"inhalt.htm		#Inhalt",
"1.htm		#§ 1 Geltungsbereich von Unfallverhütungsvorschriften",
"2.htm		#§ 2 Grundpflichten des Unternehmers",
"3.htm		#§ 3 Beurteilung der Arbeitsbedingungen, Dokumentation, Auskunftspflichten",
"4.htm		#§ 4 Unterweisung der Versicherten",
"5.htm		#§ 5 Vergabe von Aufträgen",
"6.htm		#§ 6 Zusammenarbeit mehrerer Unternehmer",
"7.htm		#§ 7 Befähigung für Tätigkeiten",
"8.htm		#§ 8 Gefährliche Arbeiten",
"9.htm		#§ 9 Zutritts- und Aufenthaltsverbote",
"10.htm		#§ 10 Besichtigung des Unternehmens, Erlass einer Anordnung, Auskunftspflicht",
"11.htm		#§ 11 Maßnahmen bei Mängeln",
"12.htm		#§ 12  Zugang zu Vorschriften und Regeln",
"13.htm		#§ 13 Pflichtenübertragung",
"14.htm		#§ 14 Ausnahmen",
"15.htm		#§ 15 Allgemeine Unterstützungspflichten und Verhalten",
"16.htm		#§ 16 Besondere Unterstützungspflichten",
"17.htm		#§ 17 Benutzung von Einrichtungen, Arbeitsmitteln und Arbeitsstoffen",
"18.htm		#§ 18 Zutritts- und Aufenthaltsverbote",
"19.htm		#§ 19 Bestellung von Fachkräften für Arbeitssicherheit und Betriebsärzten",
"20.htm		#§ 20 Bestellung und Aufgaben von Sicherheitsbeauftragten",
"21.htm		#§ 21 Allgemeine Pflichten des Unternehmers",
"22.htm		#§ 22 Notfallmaßnahmen",
"23.htm		#§ 23 Maßnahmen gegen Einflüsse des Wettergeschehens",
"24.htm		#§ 24 Allgemeine Pflichten des Unternehmers",
"25.htm		#§ 25 Erforderliche Einrichtungen und Sachmittel",
"26.htm		#§ 26 Zahl und Ausbildung der Ersthelfer",
"27.htm		#§ 27 Zahl und Ausbildung der Betriebssanitäter",
"28.htm		#§ 28 Unterstützungspflichten der Versicherten",
"29.htm		#§ 29 Bereitstellung",
"30.htm		#§ 30 Benutzung",
"31.htm		#§ 31 Besondere Unterweisungen",
"32.htm		#§ 32 Ordnungswidrigkeiten",
"33.htm		#§ 33 Aufhebung von Unfallverhütungsvorschriften",
"34.htm		#§ 34 Inkrafttreten",
"an_1.htm		#Anlage 1: Staatliche Arbeitsschutzvorschriften",
"an_2.htm		#Anlage 2: Voraussetzungen für die Ermächtigung als Stelle für die Aus- und Fortbildung in der Ersten Hilfe"
);