ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"i1.htm	#§ 1 Aufgaben des Sozialgesetzbuchs",
"i2.htm	#§ 2 Soziale Rechte",
"i3.htm	#§ 3 Bildungs-&nbsp;und Arbeitsförderung",
"i4.htm	#§ 4 Sozialversicherung",
"i5.htm	#§ 5 Soziale Entschädigung",
"i6.htm	#§ 6 Minderung des Familienaufwands",
"i7.htm	#§ 7 Zuschuß für eine angemessene Wohnung",
"i8.htm	#§ 8 Kinder-&nbsp;und Jugendhilfe",
"i9.htm	#§ 9 Sozialhilfe",
"i10.htm	#§ 10 Teilhabe behinderter Menschen",
"i11.htm	#§ 11 Leistungsarten",
"i12.htm	#§ 12 Leistungsträger",
"i13.htm	#§ 13 Aufklärung",
"i14.htm	#§ 14 Beratung",
"i15.htm	#§ 15 Auskunft",
"i16.htm	#§ 16 Antragstellung",
"i17.htm	#§ 17 Ausführung der Sozialleistungen",
"i18.htm	#§ 18 Leistungen der Ausbildungsförderung",
"i19.htm	#§ 19 Leistungen der Arbeitsförderung",
"i19a.htm	#§ 19a Leistungen der Grundsicherung für Arbeitsuchende",
"i19b.htm	#§ 19b Leistungen bei gleitendem Übergang älterer Arbeitnehmer in den Ruhestand",
"i20.htm	#§ 20 Zusätzliche Leistungen für Schwerbehinderte",
"i21.htm	#§ 21 Leistungen der gesetzlichen Krankenversicherung",
"i21a.htm	#§ 21a Leistungen der sozialen Pflegeversicherung",
"i21b.htm	#§ 21b Leistungen bei Schwangerschaftsabbrüchen",
"i22.htm	#§ 22 Leistungen der gesetzlichen Unfallversicherung",
"i23.htm	#§ 23 Leistungen der gesetzlichen Rentenversicherung",
"i24.htm	#§ 24 Leistungen der Sozialen Entschädigung",
"i24a.htm	#§ 24a Leistungen der Soldatenentschädigung",
"i25.htm	#§ 25 Kindergeld, Kinderzuschlag, Elterngeld und Leistungen für Bildung und Teilhabe",
"i26.htm	#§ 26 Wohngeld",
"i27.htm	#§ 27 Leistungen der Kinder-&nbsp;und Jugendhilfe",
"i28.htm	#§ 28 Leistungen der Sozialhilfe",
"i28a.htm	#§ 28a Leistungen der Grundsicherung",
"i29.htm	#§ 29 Leistungen zur Rehabilitation und Teilhabe behinderter Menschen",
"i30.htm	#§ 30 Geltungsbereich",
"i31.htm	#§ 31 Vorbehalt des Gesetzes",
"i32.htm	#§ 32 Verbot nachteiliger Vereinbarungen",
"i33.htm	#§ 33 Ausgestaltung von Rechten und Pflichten",
"i33a.htm	#§ 33a Altersabhängige Rechte und Pflichten",
"i33b.htm	#§ 33b Lebenspartnerschaften",
"i33c.htm	#§ 33c Benachteiligungsverbot",
"i34.htm	#§ 34 Begrenzung von Rechten und Pflichten",
"i35.htm	#§ 35 Sozialgeheimnis",
"i36.htm	#§ 36 Handlungsfähigkeit",
"i36a.htm	#§ 36a Elektronische Kommunikation",
"i37.htm	#§ 37 Vorbehalt abweichender Regelungen",
"i38.htm	#§ 38 Rechtsanspruch",
"i39.htm	#§ 39 Ermessensleistungen",
"i40.htm	#§ 40 Entstehen der Ansprüche",
"i41.htm	#§ 41 Fälligkeit",
"i42.htm	#§ 42 Vorschüsse",
"i43.htm	#§ 43 Vorläufige Leistungen",
"i44.htm	#§ 44 Verzinsung",
"i45.htm	#§ 45 Verjährung",
"i46.htm	#§ 46 Verzicht",
"i47.htm	#§ 47 Auszahlung von Geldleistungen",
"i48.htm	#§ 48 Auszahlung bei Verletzung der Unterhaltspflicht",
"i49.htm	#§ 49 Auszahlung bei Unterbringung",
"i50.htm	#§ 50 Überleitung bei Unterbringung",
"i51.htm	#§ 51 Aufrechnung",
"i52.htm	#§ 52 Verrechnung",
"i53.htm	#§ 53 Übertragung und Verpfändung",
"i54.htm	#§ 54 Pfändung",
"i55.htm	#§ 55 Kontenpfändung und Pfändung von Bargeld",
"i56.htm	#§ 56 Sonderrechtsnachfolge",
"i57.htm	#§ 57 Verzicht und Haftung des Sonderrechtsnachfolgers",
"i58.htm	#§ 58 Vererbung",
"i59.htm	#§ 59 Ausschluß der Rechtsnachfolge",
"i60.htm	#§ 60 Angabe von Tatsachen",
"i61.htm	#§ 61 Persönliches Erscheinen",
"i62.htm	#§ 62 Untersuchungen",
"i63.htm	#§ 63 Heilbehandlung",
"i64.htm	#§ 64 Leistungen zu Teilhabe am Arbeitsleben",
"i65.htm	#§ 65 Grenzen der Mitwirkung",
"i65a.htm	#§ 65a Aufwendungsersatz",
"i66.htm	#§ 66 Folgen fehlender Mitwirkung",
"i67.htm	#§ 67 Nachholung der Mitwirkung",
"i68.htm	#§ 68 Besondere Teile dieses Gesetzbuches",
"i69.htm	#§ 69 Stadtstaaten-Klausel",
"i70.htm	#§ 70 Überleitungsvorschrift Verjährungsrecht",
"i71.htm	#§ 71 Überleitungsvorschrift zur Übertragung, Verpfändung und Pfändung",
"i72.htm	#§ 72 (weggefallen)"
);