ord=new Array(
"titel.htm	#Titel",
"eingf.htm	#Eingangsformel",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Geltungsbereich",
"2.htm	#§ 2 Begriffsbestimmungen",
"3.htm	#§ 3 Anzeige",
"4.htm	#§ 4 Allgemeine Anforderungen",
"5.htm	#§ 5 Weitergehende Anforderungen",
"6.htm	#§ 6 Ausnahmebewilligung",
"7.htm	#§ 7 Prüfung durch Sachverständige",
"8.htm	#§ 8 aufgehoben",
"9.htm	#§ 9 Beschäftigungsverbot",
"10.htm	#§ 10 Ärztliche Untersuchung",
"11.htm	#§ 11 Weitere ärztliche Maßnahmen",
"12.htm	#§ 12 Allgemeine Aufgaben und Erreichbarkeit des ermächtigten Arztes",
"13.htm	#§ 13 Ermächtigte Ärzte",
"14.htm	#§ 14 Veranlassung der ärztlichen Maßnahmen",
"15.htm	#§ 15 (aufgehoben)",
"16.htm	#§ 16 (aufgehoben)",
"17.htm	#§ 17 Krankendruckluftkammern, Erholungsräume und sanitäre Einrichtungen",
"18.htm	#§ 18 Bestellung von Fachkräften",
"19.htm	#§ 19 Nachweise",
"20.htm	#§ 20 Belehrung der Arbeitnehmer",
"21.htm	#§ 21 Ausschleusungs-&nbsp;und Wartezeiten",
"22.htm	#§ 22 Straftaten und Ordnungswidrigkeiten nach dem Arbeitsschutzgesetz",
"22a.htm	#§ 22a Ordnungswidrigkeit nach dem Jugendarbeitsschutzgesetz",
"23.htm	#§ 23 Ordnungswidrigkeiten nach dem Arbeitszeitgesetz",
"24.htm	#§ 24 (weggefallen)",
"25.htm	#§ 25 (weggefallen)",
"26.htm	#§ 26 Inkrafttreten",
"anh_1.htm	#Anhang 1 (§§ 4 und 17 Abs. 2 der Verordnung über Arbeiten in Druckluft)",
"anh_2.htm	#Anhang 2 (zu § 21 Abs. 1), Ausschleusungs- und Wartezeiten",
"anh_3.htm	#Anhang 3 (Nach § 18 Abs. 1 Nr. 4 der Verordnung über Arbeiten in Druckluft)"
);