ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Anwendungsbereich",
"2.htm	#§ 2 Begriffsbestimmungen",
"3.htm	#§ 3 Einstufung von Biostoffen in Risikogruppen",
"4.htm	#§ 4: Gefährdungsbeurteilung",
"5.htm	#§ 5: Tätigkeiten mit Schutzstufenzuordnung",
"6.htm	#§ 6: Tätigkeiten ohne Schutzstufenzuordnung",
"7.htm	#§ 7: Dokumentation der Gefährdungsbeurteilung und Aufzeichnungspflichten",
"8.htm	#§ 8: Grundpflichten",
"9.htm	#§ 9: Allgemeine Schutzmaßnahmen",
"10.htm	#§ 10: Zusätzliche Schutzmaßnahmen und Anforderungen bei Tätigkeiten der Schutzstufe 2, 3 oder 4 in Laboratorien, in der Versuchstierhaltung sowie in der Biotechnologie",
"11.htm	#§ 11: Zusätzliche Schutzmaßnahmen und Anforderungen in Einrichtungen des Gesundheitsdienstes",
"12.htm	#§ 12: Arbeitsmedizinische Vorsorge",
"13.htm	#§ 13: Betriebsstörungen, Unfälle",
"14.htm	#§ 14: Betriebsanweisung und Unterweisung der Beschäftigten",
"15.htm	#§ 15: Erlaubnispflicht",
"16.htm	#§ 16: Anzeigepflicht",
"17.htm	#§ 17: Unterrichtung der Behörde",
"18.htm	#§ 18: Behördliche Ausnahmen",
"19.htm	#§ 19: Ausschuss für Biologische Arbeitsstoffe",
"20.htm	#§ 20: Ordnungswidrigkeiten",
"21.htm	#§ 21: Straftaten",
"22.htm	#§ 22: Übergangsvorschriften",
"anhang1.htm	#Anhang I Symbol für Biogefährdung",
"anhang2.htm	#Anhang II Zusätzliche Schutzmaßnahmen bei Tätigkeiten in Laboratorien und vergleichbaren Einrichtungen sowie in der Versuchstierhaltung",
"anhang3.htm	#Anhang III Zusätzliche Schutzmaßnahmen bei Tätigkeiten in der Biotechnologie"
);