ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"1.htm	#1 Anwendungsbereich",
"2.htm	#2 Begriffsbestimmungen und Erläuterungen",
"3.htm	#3 Verwendungsbeschränkungen und Ausnahmen",
"4.htm	#4 Erlaubnis, Befähigungsschein, Sachkunde",
"5.htm	#5 Gefährdungsbeurteilung",
"6.htm	#6 Aufbewahrung und Lagerung von Begasungsmitteln",
"7.htm	#7 Mitteilung an bzw. Unterrichtung der zuständigen Behörde",
"8.htm	#8 Kennzeichnung begaster Transporteinheiten und Räume",
"9.htm	#9 Entsorgung von Begasungsmittelrückständen",
"10.htm	#10 Freigabe",
"11.htm	#11 Begasungsniederschrift",
"12.htm	#12 Ergänzende Vorschriften für bestimmte Begasungsmittel",
"13.htm	#13 Zusätzlich erläuternde Hinweise",
"14.htm	#14 Mitgeltende Bestimmungen",
"15.htm	#15 Hinweise auf begleitende Regelungen bei Begasungen",
"anl.htm	#Anlagen",
"anl_1a.htm	#Anlage 1a zu TRGS 512",
"anl_1b.htm	#Anlage 1b zu TRGS 512",
"anl_1c.htm	#Anlage 1c zu TRGS 512",
"anl_1d.htm	#Anlage 1d zu TRGS 512",
"anl_1e.htm	#Anlage 1e zu TRGS 512",
"anl_2a.htm	#Anlage 2a zu TRGS 512",
"anl_2b.htm	#Anlage 2b zu TRGS 512",
"anl_3a.htm	#Anlage 3a zu TRGS 512",
"anl_3b.htm	#Anlage 3b zu TRGS 512",
"anl_3c.htm	#Anlage 3c zu TRGS 512",
"anl_3d.htm	#Anlage 3d zu TRGS 512",
"anl_4.htm	#Anlage 4 zu TRGS 512"
);