ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Anwendungsbereich und Zielsetzung",
"2.htm	#§ 2 Begriffsbestimmungen",
"3.htm	#§ 3 Gefährdungsbeurteilung",
"4.htm	#§ 4 Grundpflichten des Arbeitgebers",
"5.htm	#§ 5 Anforderungen an die zur Verfügung gestellten Arbeitsmittel",
"6.htm	#§ 6 Grundlegende Schutzmaßnahmen bei der Verwendung von Arbeitsmitteln",
"7.htm	#§ 7 Vereinfachte Vorgehensweise bei der Verwendung von Arbeitsmitteln",
"8.htm	#§ 8 Schutzmaßnahmen bei Gefährdungen durch Energien, Ingangsetzen und Stillsetzen",
"9.htm	#§ 9 Weitere Schutzmaßnahmen bei der Verwendung von Arbeitsmitteln",
"10.htm	#§ 10 Instandhaltung und Änderung von Arbeitsmitteln",
"11.htm	#§ 11 Besondere Betriebszustände, Betriebsstörungen und Unfälle",
"12.htm	#§ 12 Unterweisung und besondere Beauftragung von Beschäftigten",
"13.htm	#§ 13 Zusammenarbeit verschiedener Arbeitgeber",
"14.htm	#§ 14 Prüfung von Arbeitsmitteln",
"15.htm	#§ 15 Prüfung vor Inbetriebnahme und vor Wiederinbetriebnahme nach prüfpflichtigen Änderungen",
"16.htm	#§ 16 Wiederkehrende Prüfung",
"17.htm	#§ 17 Prüfaufzeichnungen und -bescheinigungen",
"18.htm	#§ 18 Erlaubnispflicht",
"19.htm	#§ 19 Mitteilungspflichten, behördliche Ausnahmen",
"20.htm	#§ 20 Sonderbestimmungen für überwachungsbedürftige Anlagen des Bundes",
"21.htm	#§ 21 Ausschuss für Betriebssicherheit",
"22.htm	#§ 22 Ordnungswidrigkeiten",
"23.htm	#§ 23 Straftaten",
"24.htm	#§ 24 Übergangsvorschriften",
"anh1.htm	#Anhang 1: Besondere Vorschriften für bestimmte Arbeitsmittel",
"anh2.htm	#Anhang 2: Prüfvorschriften für überwachungsbedürftige Anlagen",
"anh3.htm	#Anhang 3: Prüfvorschriften für bestimmte Arbeitsmittel"
);