ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Zielsetzung und Anwendungsbereich",
"2.htm	#§ 2 Begriffsbestimmungen",
"3.htm	#§ 3 Grundpflichten des Arbeitgebers",
"4.htm	#§ 4 Allgemeine Grundsätze",
"5.htm	#§ 5 Beurteilung der Arbeitsbedingungen",
"6.htm	#§ 6 Dokumentation",
"7.htm	#§ 7 Übertragung von Aufgaben",
"8.htm	#§ 8 Zusammenarbeit mehrerer Arbeitgeber",
"9.htm	#§ 9 Besondere Gefahren",
"10.htm	#§ 10 Erste Hilfe und sonstige Notfallmaßnahmen",
"11.htm	#§ 11 Arbeitsmedizinische Vorsorge",
"12.htm	#§ 12 Unterweisung",
"13.htm	#§ 13 Verantwortliche Personen",
"14.htm	#§ 14 Unterrichtung und Anhörung der Beschäftigten des öffentlichen Dienstes",
"15.htm	#§ 15 Pflichten der Beschäftigten",
"16.htm	#§ 16 Besondere Unterstützungspflichten",
"17.htm	#§ 17 Rechte der Beschäftigten",
"18.htm	#§ 18 Verordnungsermächtigungen",
"19.htm	#§ 19 Rechtsakte der EG und zwischenstaatliche Vereinbarungen",
"20.htm	#§ 20 Regelungen für den öffentlichen Dienst",
"20a.htm	#§ 20a Gemeinsame deutsche Arbeitsschutzstrategie",
"20b.htm	#§ 20b Nationale Arbeitsschutzkonferenz",
"21.htm	#§ 21 Zuständige Behörden;&nbsp;Zusammenwirken mit den Trägern der gesetzlichen Unfallversicherung",
"22.htm	#§ 22 Befugnisse der zuständigen Behörden",
"23.htm	#§ 23 Betriebliche Daten, Zusammenarbeit mit anderen Behörden, Jahresbericht, Bundesfachstelle",
"24.htm	#§ 24 Ermächtigung zum Erlaß von allgemeinen Verwaltungsvorschriften",
"24a.htm	#§ 24a Ausschuss für Sicherheit und Gesundheit bei der Arbeit",
"25.htm	#§ 25 Bußgeldvorschriften",
"26.htm	#§ 26 Strafvorschriften"
);