ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Zielsetzung und Anwendungsbereich",
"2.htm	#§ 2 Begriffsbestimmungen",
"3.htm	#§ 3 Gefährlichkeitsmerkmale",
"4.htm	#§ 4 Einstufung, Kennzeichnung und Verpackung",
"5.htm	#§ 5 Sicherheitsdatenblatt und sonstige Informationspflichten",
"5a.htm	#§ 5a Besondere Mitwirkungs- und Informationspflichten für Veranlasser von Tätigkeiten an baulichen oder technischen Anlagen",
"6.htm	#§ 6 Informationsermittlung und Gefährdungsbeurteilung",
"7.htm	#§ 7 Grundpflichten",
"8.htm	#§ 8 Allgemeine Schutzmaßnahmen",
"9.htm	#§ 9 Zusätzliche Schutzmaßnahmen",
"10.htm	#§ 10 Besondere Schutzmaßnahmen bei Tätigkeiten mit krebserzeugenden, keimzellmutagenen oder reproduktionstoxischen Gefahrstoffen der Kategorie 1A oder 1B",
"10a.htm	#§ 10a Besondere Aufzeichnungs-, Mitteilungs- und Unterrichtungspflichten bei Tätigkeiten mit krebserzeugenden, keimzellmutagenen oder reproduktionstoxischen Gefahrstoffen der Kategorie 1A oder 1B",
"11.htm	#§ 11 Verwendungs- und Tätigkeitsbeschränkungen für Asbest",
"11a.htm	#§ 11a Anforderungen an Tätigkeiten mit Asbest",
"12.htm	#§ 12 Besondere Schutzmaßnahmen gegen physikalisch-chemische Einwirkungen, insbesondere gegen Brand- und Explosionsgefährdungen",
"13.htm	#§ 13 Betriebsstörungen, Unfälle und Notfälle",
"14.htm	#§ 14 Unterrichtung und Unterweisung der Beschäftigten",
"15.htm	#§ 15 Zusammenarbeit verschiedener Firmen",
"15a.htm #§ 15a Verwendungsbeschränkungen",
"15b.htm #§ 15b Allgemeine Anforderungen an die Verwendung von Biozid-Produkten",
"15c.htm #§ 15c Besondere Anforderungen an die Verwendung bestimmter Biozid-Produkte",
"15d.htm #§ 15d Besondere Anforderungen bei Begasungen",
"15e.htm #§ 15e Ergänzende Dokumentationspflichten",
"15f.htm #§ 15f Anforderungen an den Umgang mit Transporteinheiten",
"15g.htm #§ 15g Besondere Anforderungen an Begasungen auf Schiffen",
"15h.htm #§ 15h Ausnahmen von Abschnitt 4a",
"16.htm	#§ 16 Herstellungs- und Verwendungsbeschränkungen",
"17.htm	#§ 17 Nationale Ausnahmen von Beschränkungsregelungen nach der Verordnung (EG) Nr. 1907/2006",
"18.htm	#§ 18 Unterrichtung der Behörde",
"19.htm	#§ 19 Behördliche Ausnahmen, Anordnungen und Befugnisse",
"19a.htm #§ 19a Anerkennung ausländischer Qualifikationen",
"20.htm	#§ 20 Ausschuss für Gefahrstoffe",
"21.htm	#§ 21 Chemikaliengesetz &ndash; Anzeigen",
"22.htm	#§ 22 Chemikaliengesetz &ndash; Tätigkeiten",
"23.htm	#§ 23 (weggefallen)",
"24.htm	#§ 24 Chemikaliengesetz &ndash; Herstellungs- und Verwendungsbeschränkungen",
"25.htm	#§ 25 Übergangsvorschrift",
"anh1_1.htm	#Anhang I: Nummer 1: Brand- und Explosionsgefährdungen",
"anh1_2.htm	#Anhang I: Nummer 2: Partikelförmige Gefahrstoffe",
"anh1_3.htm	#Anhang I: Nummer 3: Asbest",
"anh1_4.htm	#Anhang I: Nummer 4: Biozid-Produkte und Begasung mit Biozid-Produkten oder Pflanzenschutzmitteln",
"anh1_5.htm	#Anhang I: Nummer 5: Ammoniumnitrat",
"anh2_1.htm	#Anhang II: Nummer 1: (weggefallen)",
"anh2_2.htm	#Anhang II: Nummer 2: 2-Naphthylamin, 4-Aminobiphenyl, Benzidin, 4-Nitrobiphenyl",
"anh2_3.htm	#Anhang II: Nummer 3: (weggefallen)",
"anh2_4.htm	#Anhang II: Nummer 4: Kühlschmierstoffe und Korrosionsschutzmittel",
"anh2_5.htm	#Anhang II: Nummer 5: Biopersistente Fasern",
"anh2_6.htm	#Anhang II: Nummer 6: Besonders gefährliche krebserzeugende Stoffe",
"anh3_1.htm	#Anhang III: Nummer 1: Anwendungsbereich und Begriffsbestimmungen",
"anh3_2.htm	#Anhang III: Nummer 2: Tätigkeiten mit organischen Peroxiden"
);