ord=new Array(
"titel.htm	#Titelseite",
"inhalt.htm	#Inhalt",
"00.htm	#Vorbemerkung",
"01.htm	#§ 1  Anwendungsbereich",
"02.htm	#§ 2 Begriffsbestimmungen",
"03.htm	#§ 3  Allgemeine Anforderungen",
"04.htm	#§ 4  Beurteilung der Expositionsbereiche",
"05.htm	#§ 5  Betriebsanweisungen",
"06.htm	#§ 6  Bereiche erhöhter Exposition, Gefahrbereiche",
"07.htm	#§ 7  Kennzeichnung und Abgrenzung",
"08.htm	#§ 8  Persönliche Schutzausrüstungen",
"09.htm	#§ 9  Prüfung",
"10.htm	#§ 10  Unterweisung",
"11.htm	#§ 11  Anlagenspezifische Dokumentation",
"12.htm	#§ 12  Mittelbare Wirkungen, Körperhilfsmittel",
"13.htm	#§ 13  Versuchsanlagen und ortsveränderliche Quellen",
"14.htm	#§ 14  Anlagen mit hohen statischen Magnetfeldern",
"15.htm	#§ 15  Instandhaltung, Erprobung",
"16.htm	#§ 16 Ordnungswidrigkeiten",
"17.htm	#§ 17 Übergangs- und Ausführungsbestimmungen",
"18.htm	#§ 18  Inkrafttreten",
"a_1.htm	#Anlage 1: Zulässige Werte für EM-Felder",
"a_2.htm	#Anlage 2: Zulässige Werte für Anlagen mit hohen statischen Magnetfeldern"
);