ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhaltsverzeichnis",
"1.htm	#1 Was ist Tageslicht?",
"2.htm	#2 Warum ist Tageslicht wichtig?",
"3.htm	#3 Welche Funktion hat die Sichtverbindung nach außen?",
"4.htm	#4 Was sagt der Gesetzgeber?",
"5.htm	#5 Was bedeutet möglichst ausreichend Tageslicht am Arbeitsplatz?",
"6.htm	#6 Welchen Einfluss haben Bewölkung und Jahreszeit auf den Tageslichteinfall?",
"7.htm	#7 Wie können Tageslichteinfall und Tageslichtnutzung optimiert werden?",
"8.htm	#8 Was ist zu tun, wenn Anforderungen nicht erfüllt werden können?",
"9.htm	#9 Wie tragen unterschiedliche Fensterflächen zu Tageslichteinfall und Sichtverbindung bei?",
"10.htm	#10 Was ist zu beachten, damit Tageslicht die Beschäftigten nicht stört?",
"11.htm	#11 Welchen Einfluss hat die Art der Verglasung?",
"12.htm	#12 Welche Arten von Dachoberlichtern gibt es?",
"13.htm	#13 Wann sollten Fenster, wann Dachoberlichter verwendet werden?",
"14.htm	#14 Spart Tageslicht Energiekosten?",
"15.htm	#15 Fensterputzen, muss das sein?",
"16.htm	#16 Wo gibt es weiterführende Informationen?",
"anh.htm	#Anhang",
"glossar.htm	#Glossar"
);