ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Zweck des Gesetzes",
"2.htm	#§ 2 Begriffsbestimmungen",
"3.htm	#§ 3 Arbeitszeit der Arbeitnehmer",
"4.htm	#§ 4 Ruhepausen",
"5.htm	#§ 5 Ruhezeit",
"6.htm	#§ 6 Nacht- und Schichtarbeit",
"7.htm	#§ 7 Abweichende Regelungen",
"8.htm	#§ 8 Gefährliche Arbeiten",
"9.htm	#§ 9 Sonn-&nbsp;und Feiertagsruhe",
"10.htm	#§ 10 Sonn-&nbsp;und Feiertagsbeschäftigung",
"11.htm	#§ 11 Ausgleich für Sonn- und Feiertagsbeschäftigung",
"12.htm	#§ 12 Abweichende Regelungen",
"13.htm	#§ 13 Ermächtigung, Anordnung, Bewilligung",
"14.htm	#§ 14 Außergewöhnliche Fälle",
"15.htm	#§ 15 Bewilligung, Ermächtigung",
"16.htm	#§ 16 Aushang und Arbeitszeitnachweise",
"17.htm	#§ 17 Aufsichtsbehörde",
"18.htm	#§ 18 Nichtanwendung des Gesetzes",
"19.htm	#§ 19 Beschäftigung im öffentlichen Dienst",
"20.htm	#§ 20 Beschäftigung in der Luftfahrt",
"21.htm	#§ 21 Beschäftigung in der Binnenschiffahrt",
"21a.htm#§ 21a Beschäftigung im Straßentransport",
"22.htm	#§ 22 Bußgeldvorschriften",
"23.htm	#§ 23 Strafvorschriften",
"24.htm	#§ 24 Umsetzung von zwischenstaatlichen Vereinbarungen",
"25.htm	#§ 25 Übergangsregelung für Tarifverträge",
"26.htm	#§ 26 (aufgehoben)"
);