ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Anwendungsbereich, Ziel des Mutterschutzes",
"2.htm	#§ 2 Begriffsbestimmungen",
"3.htm	#§ 3 Schutzfristen vor und nach der Entbindung",
"4.htm	#§ 4 Verbot der Mehrarbeit; Ruhezeit",
"5.htm	#§ 5 Verbot der Nachtarbeit",
"6.htm	#§ 6 Verbot der Sonn- und Feiertagsarbeit",
"7.htm	#§ 7 Freistellung für Untersuchungen und zum Stillen",
"8.htm	#§ 8 Beschränkung von Heimarbeit",
"9.htm	#§ 9 Gestaltung der Arbeitsbedingungen; unverantwortbare Gefährdung",
"10.htm	#§ 10 Beurteilung der Arbeitsbedingungen; Schutzmaßnahmen",
"11.htm	#§ 11 Unzulässige Tätigkeiten und Arbeitsbedingungen für schwangere Frauen",
"12.htm	#§ 12 Unzulässige Tätigkeiten und Arbeitsbedingungen für stillende Frauen",
"13.htm	#§ 13 Rangfolge der Schutzmaßnahmen: Umgestaltung der Arbeitsbedingungen, Arbeitsplatzwechsel und betriebliches Beschäftigungsverbot",
"14.htm	#§ 14 Dokumentation und Information durch den Arbeitgeber",
"15.htm	#§ 15 Mitteilungen und Nachweise der schwangeren und stillenden Frauen",
"16.htm	#§ 16 Ärztliches Beschäftigungsverbot",
"17.htm	#§ 17 Kündigungsverbot",
"18.htm	#§ 18 Mutterschutzlohn",
"19.htm	#§ 19 Mutterschaftsgeld",
"20.htm	#§ 20 Zuschuss zum Mutterschaftsgeld",
"21.htm	#§ 21 Ermittlung des durchschnittlichen Arbeitsentgelts",
"22.htm	#§ 22 Leistungen während der Elternzeit",
"23.htm	#§ 23 Entgelt bei Freistellung für Untersuchungen und zum Stillen",
"24.htm	#§ 24 Fortbestehen des Erholungsurlaubs bei Beschäftigungsverboten",
"25.htm	#§ 25 Beschäftigung nach dem Ende des Beschäftigungsverbots",
"26.htm	#§ 26 Aushang des Gesetzes",
"27.htm	#§ 27 Mitteilungs- und Aufbewahrungspflichten des Arbeitgebers, Offenbarungsverbot der mit der Überwachung beauftragten Personen",
"28.htm	#§ 28 Behördliches Genehmigungsverfahren für eine Beschäftigung zwischen 20 Uhr und 22 Uhr",
"29.htm	#§ 29 Zuständigkeit und Befugnisse der Aufsichtsbehörden, Jahresbericht",
"30.htm	#§ 30 Ausschuss für Mutterschutz",
"31.htm	#§ 31 Erlass von Rechtsverordnungen",
"32.htm	#§ 32 Bußgeldvorschriften",
"33.htm	#§ 33 Strafvorschriften",
"34.htm	#§ 34 Evaluationsbericht"
);