

// Aufbau de Tabelle: 
// z.B. k_org_aso1|00', ziel: 'f_org_aso1|00
// Faktor (Kurzhh) | Maﬂnahmennummer in Kurzhh-Faktor | 


// NEU: Bei Servicebranchen soll nach f_org_s_aso ¸bernommen werden; nicht nach f_org_aso2:
var f_org_aso2_name='f_org_aso2';

if (bereich=="gebrein_k" ||bereich=="fm_k" ||bereich=="schornsteinfeger_k" ||bereich=="klett_k"  ||bereich=="taucher_k" ||bereich=="boot_k")  
  f_org_aso2_name='f_org_s_aso2';
//

var konv_tab=new Array(
{quelle:'k_org_aso1|00', ziel: 'f_org_aso1|00'},
{quelle:'k_org_aso1|01', ziel: 'f_org_aso1|06'},
{quelle:'k_org_aso1|02', ziel: 'f_org_aso1|07'},
{quelle:'k_org_aso1|03', ziel: 'f_org_aso1|10'},
{quelle:'k_org_aso1|04', ziel: f_org_aso2_name+'|05'},
{quelle:'k_org_aso1|05', ziel: f_org_aso2_name+'|06'},
{quelle:'k_org_aso1|06', ziel: f_org_aso2_name+'|08'},
{quelle:'k_org_aso1|07', ziel: 'f_brunnenbau|05'},
{quelle:'k_org_aso1|08', ziel: 'f_arbeiten_wasser|02'},
{quelle:'k_org_aso1|09', ziel: 'f_org_aso1|04'},
{quelle:'k_org_aso1|10', ziel: 'f_brunnenbau|06'},
{quelle:'k_org_aso1|11', ziel: 'f_abbruch_grossger_|17'},
{quelle:'k_org_aso1|12', ziel: 'f_abbruch_allgemein|08'},
{quelle:'k_org_aso1|13', ziel: 'f_abbruch_allgemein|05'},
{quelle:'k_org_aso1|14', ziel: 'f_brunnenbau|04'},
{quelle:'k_org_aso1|15', ziel: 'f_spezialtiefbau_zusatz|05'},
{quelle:'k_org_aso1|16', ziel: 'f_spezialtiefbau_zusatz|04'},
{quelle:'k_org_aso1|90', ziel: 'f_org_aso1|12'},

{quelle:'k_absturz1|00', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|22'},
{quelle:'k_absturz1|00', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|23'},
{quelle:'k_absturz1|00', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|24'},
{quelle:'k_absturz1|00', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|25'},
{quelle:'k_absturz1|01', ziel: 'f_schlitzlamelle_absturz_|00'},
{quelle:'k_absturz1|01', ziel: 'f_schlitzlamelle_absturz_|02'},
{quelle:'k_absturz1|02', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|22'},
{quelle:'k_absturz1|02', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|23'},
{quelle:'k_absturz1|02', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|24'},
{quelle:'k_absturz1|02', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|25'},
{quelle:'k_absturz1|03', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|14'},
{quelle:'k_absturz1|04', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|16'},
{quelle:'k_absturz1|05', ziel: 'f_geruest_standsicherheit|02'},
{quelle:'k_absturz1|06', ziel: 'f_geruest_pruef|03'},
{quelle:'k_absturz1|07', ziel: 'f_gerueste_benutzung|02'},
{quelle:'k_absturz1|08', ziel: 'f_arbeit_dach|26'},
{quelle:'k_absturz1|09', ziel: 'f_arbeit_dach|30'},
{quelle:'k_absturz1|10', ziel: 'f_kleingeruest_fahrb_arbeitsbuehne|01'},
{quelle:'k_absturz1|11', ziel: 'f_fassade_|07'},
{quelle:'k_absturz1|12', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|29'},
{quelle:'k_absturz1|13', ziel: 'f_auffangnetze|00'},
{quelle:'k_absturz1|14', ziel: 'f_auffangnetze|04'},
{quelle:'k_absturz1|15', ziel: 'f_hochgelegene_AP|01'},
{quelle:'k_absturz1|16', ziel: 'f_hochgelegene_AP|03'},
{quelle:'k_absturz1|17', ziel: 'f_brunnenbau|07'},
{quelle:'k_absturz1|18', ziel: 'f_bockgeruest|00'},
{quelle:'k_absturz1|90', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|30'},

{quelle:'k_stolpern1|00', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|03'},
{quelle:'k_stolpern1|01', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|04'},
{quelle:'k_stolpern1|90', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|31'},

{quelle:'k_maschinen1|00', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|08'},
{quelle:'k_maschinen1|01', ziel: 'f_fahrzeuge_Baustel|12'},
{quelle:'k_maschinen1|02', ziel: 'f_hebezeugeinsatz_|04'},
{quelle:'k_maschinen1|03', ziel: 'f_material_geraete_transp|00'},
{quelle:'k_maschinen1|04', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|07'},
{quelle:'k_maschinen1|05', ziel: 'f_absicherung_baustellen|06'},
{quelle:'k_maschinen1|06', ziel: 'f_laufd_schienenverk|02'},
{quelle:'k_maschinen1|07', ziel: 'f_kettensaegen_|00'},
{quelle:'k_maschinen1|08', ziel: 'f_holzbearbeitung_|07'},
{quelle:'k_maschinen1|09', ziel: 'f_strahlen_hochdruckwass_|05'},
{quelle:'k_maschinen1|09', ziel: 'f_strahlen_hochdruckwass_|06'},
{quelle:'k_maschinen1|09', ziel: 'f_strahlen_hochdruckwass_|07'},
{quelle:'k_maschinen1|09', ziel: 'f_strahlen_hochdruckwass_|08'},
{quelle:'k_maschinen1|09', ziel: 'f_strahlen_hochdruckwass_|09'},
{quelle:'k_maschinen1|10', ziel: 'f_strahlen_hochdruckwass_|15'},
{quelle:'k_maschinen1|11', ziel: 'f_spezialtiefbau_|16'},
{quelle:'k_maschinen1|12', ziel: 'f_tauch_pontons|01'},
{quelle:'k_maschinen1|13', ziel: 'f_erd_straszen_baum|18'},
{quelle:'k_maschinen1|14', ziel: 'f_kernbohren|04'},
{quelle:'k_maschinen1|15', ziel: 'f_abbruch_masch_betonbohr|15'},
{quelle:'k_maschinen1|16', ziel: 'f_kernbohren|15'},
{quelle:'k_maschinen1|17', ziel: 'f_abbruch_masch_betonbohr|04'},
{quelle:'k_maschinen1|90', ziel: 'f_org_aso2|09'},

{quelle:'k_bauteile1|00', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen_stat|03'},
{quelle:'k_bauteile1|01', ziel: 'f_brunnenbau|09'},
{quelle:'k_bauteile1|02', ziel: 'f_hebezeugeinsatz_|00'},
{quelle:'k_bauteile1|03', ziel: 'f_material_geraete_transp|06'},
{quelle:'k_bauteile1|04', ziel: 'f_bauaufzug|10'},
{quelle:'k_bauteile1|05', ziel: 'f_hubarbeitsbuehne|03'},
{quelle:'k_bauteile1|06', ziel: 'f_aufrichten_|00'},
{quelle:'k_bauteile1|07', ziel: 'f_montage_konstrukt|06'},
{quelle:'k_bauteile1|08', ziel: 'f_montage_konstrukt|22'},
{quelle:'k_bauteile1|09', ziel: 'f_montage_konstrukt|23'},
{quelle:'k_bauteile1|09', ziel: 'f_montage_konstrukt|24'},
{quelle:'k_bauteile1|09', ziel: 'f_montage_konstrukt|25'},
{quelle:'k_bauteile1|10', ziel: 'f_traggerueste|03'},
{quelle:'k_bauteile1|11', ziel: 'f_traggerueste|04'},
{quelle:'k_bauteile1|12', ziel: 'f_Baugruben|01'},
{quelle:'k_bauteile1|13', ziel: 'f_Baugruben|02'},
{quelle:'k_bauteile1|14', ziel: 'f_Baugruben|04'},
{quelle:'k_bauteile1|15', ziel: 'f_Baugruben|14'},
{quelle:'k_bauteile1|16', ziel: 'f_abbruch_allgemein|20'},
{quelle:'k_bauteile1|17', ziel: 'f_spezialtiefbau_|16'},
{quelle:'k_bauteile1|18', ziel: 'f_brunnenbau|08'},
{quelle:'k_bauteile1|19', ziel: 'f_brunnenbau|01'},
{quelle:'k_bauteile1|20', ziel: 'f_fahrzeuge_Baustel|27'},
{quelle:'k_bauteile1|21', ziel: 'f_abbruch_allgemein|03'},
{quelle:'k_bauteile1|90', ziel: 'f_arbeitsplatz_verkehrsweg_anlegen|32'},

{quelle:'k_elektr-strom1|00', ziel: 'f_elektrischer_strom|00'},
{quelle:'k_elektr-strom1|01', ziel: 'f_elektrischer_strom|04'},
{quelle:'k_elektr-strom1|02', ziel: 'f_elektrischer_strom|04'},
{quelle:'k_elektr-strom1|03', ziel: 'f_elektrischer_strom|04'},
{quelle:'k_elektr-strom1|04', ziel: 'f_elektr_anl_|01'},
{quelle:'k_elektr-strom1|05', ziel: 'f_enge_raeume|01'},
{quelle:'k_elektr-strom1|06', ziel: 'f_enge_raeume|01'},
{quelle:'k_elektr-strom1|07', ziel: 'f_abbruch_masch_betonbohr|92'},
{quelle:'k_elektr-strom1|90', ziel: 'f_elektrischer_strom|07'},

{quelle:'k_gefahrstoffe1|00', ziel: 'f_gefahrstoff_allg|00'},
{quelle:'k_gefahrstoffe1|01', ziel: 'f_gefahrstoff_allg|01'},
{quelle:'k_gefahrstoffe1|02', ziel: 'f_staub_allg|02'},
{quelle:'k_gefahrstoffe1|03', ziel: 'f_staub_allg|02'},
{quelle:'k_gefahrstoffe1|04', ziel: 'f_staub_allg|02'},
{quelle:'k_gefahrstoffe1|05', ziel: 'f_staub_allg|03'},
{quelle:'k_gefahrstoffe1|06', ziel: 'f_entfernen_holzschutzzm_|00'},
{quelle:'k_gefahrstoffe1|07', ziel: 'f_kmf_ausbau|02'},
{quelle:'k_gefahrstoffe1|08', ziel: 'f_staub_allg|04'},
{quelle:'k_gefahrstoffe1|09', ziel: 'f_staub_holz|03'},
{quelle:'k_gefahrstoffe1|10', ziel: 'f_zement|02'},
{quelle:'k_gefahrstoffe1|11', ziel: 'f_Feuchtarbeit_|01'},
{quelle:'k_gefahrstoffe1|12', ziel: 'f_rohrleitungen_arbeit_in_|06'},
{quelle:'k_gefahrstoffe1|90', ziel: 'f_gefahrstoff_allg|16'},

{quelle:'k_laerm1|00', ziel: 'f_laerm|12'},
{quelle:'k_laerm1|01', ziel: 'f_laerm|09'},
{quelle:'k_laerm1|90', ziel: 'f_laerm|15'},

{quelle:'k_brand-explosion1|00', ziel: 'f_fluessiggas|01'},
{quelle:'k_brand-explosion1|01', ziel: 'f_brandgefahren_|07'},
{quelle:'k_brand-explosion1|02', ziel: 'f_gefahrstoff_allg|03'},
{quelle:'k_brand-explosion1|03', ziel: 'f_brunnenbau|11'},
{quelle:'k_brand-explosion1|90', ziel: 'f_brandgefahren_|12'},

{quelle:'k_brand-explosion1|00', ziel: 'f_elektromagnFeld_|06'},
{quelle:'k_brand-explosion1|90', ziel: 'f_elektromagnFeld_|07'},

{quelle:'k_biolog-stoffe1|00', ziel: 'f_schimmel_tauben|00'},
{quelle:'k_biolog-stoffe1|01', ziel: 'f_schimmel_tauben|01'},
{quelle:'k_biolog-stoffe1|02', ziel: 'f_schimmel_tauben|01'},
{quelle:'k_biolog-stoffe1|90', ziel: 'f_schimmel_tauben|16'},

{quelle:'k_phys-belastung1|00', ziel: 'f_koerplueberl_Hochbau_|13'},
{quelle:'k_phys-belastung1|01', ziel: 'f_koerplueberl_Hochbau_|01'},
{quelle:'k_phys-belastung1|02', ziel: 'f_koerplueberl_Hochbau_|18'},
{quelle:'k_phys-belastung1|03', ziel: 'f_koerplueberl_Hochbau_|28'},
{quelle:'k_phys-belastung1|04', ziel: 'f_koerplueberl_Hochbau_|17'},
{quelle:'k_phys-belastung1|05', ziel: 'f_koerplueberl_Hochbau_|29'},
{quelle:'k_phys-belastung1|90', ziel: 'f_koerplueberl_Hochbau_|23'},

{quelle:'k_psych-belastung1|00', ziel: 'f_org_s_baudurchfuehrung|01'},
{quelle:'k_psych-belastung1|01', ziel: 'f_org_baudurchfuehrung|01'},
{quelle:'k_psych-belastung1|02', ziel: 'f_org_s_fuehren|01'},
{quelle:'k_psych-belastung1|03', ziel: 'f_org_fuehren|01'},
{quelle:'k_psych-belastung1|04', ziel: 'f_org_s_fuehren|06'},
{quelle:'k_psych-belastung1|05', ziel: 'f_org_fuehren|06'},
{quelle:'k_psych-belastung1|06', ziel: 'f_org_s_personaleinsatz|09'},
{quelle:'k_psych-belastung1|07', ziel: 'f_org_personaleinsatz|09'},
{quelle:'k_psych-belastung1|08', ziel: 'f_org_aso1|17'},
{quelle:'k_psych-belastung1|09', ziel: 'f_org_s_arbeitsorganisation|28'},
{quelle:'k_psych-belastung1|10', ziel: 'f_org_arbeitsorganisation|28'},
{quelle:'k_psych-belastung1|90', ziel: 'f_org_arbeitsorganisation|23'},

{quelle:'k_fahrz-oeff-verkehr1|00', ziel: 'f_Fahrz÷ffVer_|00'},
{quelle:'k_fahrz-oeff-verkehr1|01', ziel: 'f_Fahrz÷ffVer_|12'},
{quelle:'k_fahrz-oeff-verkehr1|02', ziel: 'f_Fahrz÷ffVer_|02'},
{quelle:'k_fahrz-oeff-verkehr1|03', ziel: 'f_Fahrz÷ffVer_|05'},
{quelle:'k_fahrz-oeff-verkehr1|04', ziel: 'f_Fahrz÷ffVer_|03'},
{quelle:'k_fahrz-oeff-verkehr1|05', ziel: 'f_Fahrz÷ffVer_|04'},
{quelle:'k_fahrz-oeff-verkehr1|06', ziel: 'f_Fahrz÷ffVer_|11'},
{quelle:'k_fahrz-oeff-verkehr1|90', ziel: 'f_Fahrz÷ffVer_|06'}
);
