/*
ga_dateien=new Array();
datum=new Array();
titel=new Array();
gefahr=new Array();
fragen=new Array();
hinweis_neu=new Array();
massnahmen=new Array();
z=0;
*/
//------------------------------------------------------';
//------------------------------------------------------';
//------------------------------------------------------';

//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_org_aso1']=z;
datum[z]='250318';
titel[z]='Arbeitsschutzorganisation';
gefahr[z]='Gefährdungsfaktoren: Mängel in der Arbeitsorganisation; Psychische Fehlbeanspruchungen';
fragen[z]='Wie werden Mängel in der <a href="'+xpath+'ga_bau/f_iop/iop0342.htm">Arbeitsschutzorganisation</a> vermieden?';
m[x++]='00:Für den Auftrag sind fachlich geeignete Vorgesetzte und weisungsbefugte Aufsichtführende festgelegt.#A 001,G 808';
m[x++]='01:Die Beschäftigten werden regelmäßig zu allen Themen unterwiesen. Auch die ausländischen Beschäftigten verstehen die Informationen.#G 807';
m[x++]='02:Die Betriebsanweisungen für die verwendeten Arbeitsmittel und Gefahrstoffe sind erstellt.#A 042';
m[x++]='03:Die Fristen für die Prüfung der Arbeitsmittel und die befähigten Personen zur Prüfung der Arbeitsmittel sind festgelegt.#A 007';
m[x++]='04:Beschäftigten stehen die für ihre Arbeitsaufgaben erforderliche Persönliche Schutzausrüstung sowie die erforderlichen Hautschutzmittel zur Verfügung. Die Beschäftigten sind angewiesen, diese zu benutzen.#G 808';
m[x++]='05:Für Arbeiten bei besonderen Witterungseinwirkungen (zum Beispiel Kälte, Sonneneinwirkung, Zugluft, Regen) sind entsprechende Maßnahmen festgelegt. (Kleidung, Sonnenschutz, Möglichkeiten zum Aufbewahren und Trocknen der Kleidung).#D 505,E 606';
m[x++]='06:Die erforderlichen Erste-Hilfe-Maßnahmen und Brandschutz-Maßnahmen für die Baustelle sind umgesetzt.#A 004,A 021';
m[x++]='07:Die erforderlichen Erste-Hilfe-Maßnahmen und Brandschutz-Maßnahmen für Räume unter Erdgleiche/ untertägige Räume sind umgesetzt.#A 004,A 021,A 063';
m[x++]='08:Die erforderlichen Notfall-Maßnahmen bei Arbeiten über Wasser sind umgesetzt.#C 480';
m[x++]='09:Arbeitsmedizinische Vorsorge wurde durchgeführt, bzw. angeboten. Beratung durch Betriebsarzt.#D 513';
m[x++]='10:Bei Gefährdung durch Wasserandrang spezielle Flucht- und Rettungsmaßnahmen planen.#A 006';
m[x++]='11:Abbruchanweisung liegt vor und wird beim Arbeitsablauf umgesetzt.#C 301';
m[x++]='12:Abbruch-/ Rückbauanweisung liegt vor und wird beim Arbeitsablauf umgesetzt.#C 301';
m[x++]='13:Vorerkundungen über Lage von Versorgungsleitungen (Strom, Gas, Wasser, …) (18.1.2018)#C 365';
m[x++]='14:Für Bohrarbeiten in kontaminierten Bereichen spezielle Gefährdungsbeurteilung anfertigen.#C 316,B 184';
m[x++]='15:Baugrund frei von Kontamination und Kampfmitteln, erdverlegte Leitungen freigeschaltet.#C 316,C 472';
m[x++]='16:';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_absturz1']=z;
datum[z]='180216';
titel[z]='Gefährdung durch Absturz';
gefahr[z]='Gefährdungsfaktoren: Absturz';
fragen[z]='Welche Maßnahmen werden gegen <a href="'+xpath+'ga_bau/f_a/a10061.htm">Gefährdungen durch Absturz</a> ergriffen?';
m[x++]='00:Öffnungen und Kanten absperren, abdecken, Seitenschutz/umwehren#B 100';
m[x++]='01:Offene Brunnen / Bohrungen / Schlitze abdecken oder umwehren#B 100';
m[x++]='02:Öffnungen, Kanten und auch kleinere Bohrlöcher absperren, abdecken, Seitenschutz/umwehren#B 100';
m[x++]='03:Abmessungen/ Güte von Stand-/ Laufflächen überprüfen (z. B. Lattung, lastverteilende Beläge)#C 344,C 343';
m[x++]='04:Tragfähigkeit von Stand-/Laufflächen und von Stützkonstruktionen beachten - gemäß Aufbau- und Verwendungsanleitung - vorab bemessen#C 343,C 344';
m[x++]='05:Gerüstaufbau: Handlungsanleitung für den Umgang mit Arbeits- und Schutzgerüsten (DGUV Information 201-011) beachten#B 113,C 351,C 352';
m[x++]='06:Prüfungen von Gerüsten nach der Montage durch die befähigte Person im Gerüstbau#C 356,C 353,F 705';
m[x++]='07:Gerüste vorhalten, tägliche Sichtkontrolle für sicheres Benutzen#C 353';
m[x++]='08:Dachfanggerüst#B 121';
m[x++]='09:Dachschutzwände#B 101';
m[x++]='10:Fahrbare Arbeitsbühnen nach Aufbau- und Verwendungsanleitung aufbauen und einsetzen#B 112';
m[x++]='11:In Fassadenbefahranlagen Anseilschutz benutzen#B 149,B 147';
m[x++]='12:Für Anseilschutz geeignete Anschlagpunkte festlegen (z. B. bei kurzfristigen Arbeiten)#B 104,E 601';
m[x++]='13:Tragende Konstruktion statisch für Auffangnetze vorgesehen bzw. geeignet#C 362,B 102';
m[x++]='14:Gebrauchsanleitung des Netzherstellers beachten - Einsatzbereich - Fristen der Alterungsprüfungen#B 102';
m[x++]='15:Vor Leitereinsatz prüfen: sind sichere Arbeitsmittel ohne Absturzgefährdung einsetzbar, z. B. <a href="'+xpath+'bausteine/b_131/b_131.htm">Kleingerüste/fahrbare Arbeitsbühnen</a>, Fahrgerüste, Hubarbeitsbühnen, Podestleitern?#B 131';
m[x++]='16:Nur geeignete unbeschädigte Leitern einsetzen#B 131';
m[x++]='17:Bei Steigeisengängen Auffanggurt und tragfähige Anschlageinrichtung (z.B. Dreibock) einsetzen.#E 601,B 133';
m[x++]='18:Bockgerüste: Aufbau und Verwendung nach Herstellerangaben#B 117';
m[x++]='19:';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_stolpern1']=z;
datum[z]='180216';
titel[z]='Gefährdung durch Stolpern, Rutschen, Stürzen';
gefahr[z]='Gefährdungsfaktoren: Stolpern, Rutschen, Stürzen';
fragen[z]='Welche Maßnahmen werden gegen Gefährdung durch Stolpern, Rutschen, Stürzen ergriffen?';
m[x++]='00:Beseitigen von Hindernissen, Verschmutzungen und/oder Rutschgefahren bei Arbeitsplätzen und Verkehrswegen#A 026';
m[x++]='01:Witterungseinflüsse beachten (z.B. Nässe, Frost, Wind)#';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_maschinen1']=z;
datum[z]='180216';
titel[z]='Gefährdung durch sich bewegende Maschinen#B 365';
gefahr[z]='Gefährdungsfaktoren: sich bewegende Maschinen und zu bearbeitende Bauteile';
fragen[z]='Welche Maßnahmen werden gegen Gefährdung durch sich bewegende Maschinen und zu bearbeitende Bauteile getroffen?';
m[x++]='00:Sicherheitsabstände einhalten#';
m[x++]='01:Fahrbare Maschinen mit Rück-/Seitenraumüberwachung  einsetzen#B 181,B 182';
m[x++]='02:Hebezeugeinsatz festlegen (z. B. Ausrüstung, Koordinierung mehrerer Hebezeuge)#B 214';
m[x++]='03:Hebezeugeinsatz festlegen (z. B. Portalkran, Autokran, Teleskopstapler, Kettenzüge)#';
m[x++]='04:Verkehrswege einrichten#A 026';
m[x++]='05:Verkehrssicherung bei Arbeiten im öffentlichen Straßenraum#A 008';
m[x++]='06:Sicherungsmaßnahmen bei Arbeiten im Gleisbereich#C 431';
m[x++]='07:Besondere Arbeitsanweisungen zum Einsatz von Kettensägen#B 259';
m[x++]='08:Besondere Arbeitsanweisungen zum Einsatz von Kreissägen#B 265';
m[x++]='09:Hochdruckwasserstrahlen nur mit geeigneter PSA#B 238';
m[x++]='10:Bei Hochdruckwasserstrahlen Gefahrenbereiche festlegen und absperren.#';
m[x++]='11:Beim Verfahren von Großgeräten Tragfähigkeit, Ebenheit und Neigung des Untergrund beachten#';
m[x++]='12:Maschinenarbeiten von schwimmenden Geräten mit rechnerischem Nachweis.#B 188';
m[x++]='13:Mitgängerbetrieb  mit dafür ausgerüsteten Maschinen#B 185';
m[x++]='14:Richtige Auswahl und sichere Befestigung der eingesetzten Maschinen#C 365';
m[x++]='15:Zustand der Diamantwerkzeuge ständig kontrollieren (Bohrkronen, Sägeblätter, Seile)#C 365';
m[x++]='16:Kippgefährdete Bauteile (Tür-, Fensterausschnitte) formschlüssig sichern#C 365';
m[x++]='17:Erweiterte Gefahrenbereiche festlegen, z.B. bei Seilsägen#C 365';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_bauteile1']=z;
datum[z]='180216';
titel[z]='Gefährdung durch nicht standfeste Bauteile, umstürzende Geräte und Materialien';
gefahr[z]='Gefährdungsfaktoren: nicht standfeste Bauteile, umstürzende Geräte und Materialien';
fragen[z]='Welche Maßnahmen werden gegen Gefährdung durch nicht standfeste Bauteile, umstürzende Geräte und Materialien getroffen?';
m[x++]='00:Bei abrutschenden, herabfallenden Gegenständen: Absperrung/Kennzeichnung des gefährdeten Bereiches#';
m[x++]='01:Bei herabfallenden Einbauteilen in Brunnen, Bohrungen, Schächten: gesicherten Bereich aufsuchen#';
m[x++]='02:Montage- und Betriebsanleitung für Turmdrehkran ist auf Baustelle vorhanden, damit Auf-/Abbau und Betrieb nach Montage- und Betriebsanleitung erfolgen kann#B 213';
m[x++]='03:Lastaufnahmeeinrichtungen: geeignete  Lastaufnahmeeinrichtungen verwenden#B 161';
m[x++]='04:Betriebs- und Montageanleitung des Bauaufzuges ist auf der Baustelle vorhanden#B 142,B 143,B 145';
m[x++]='05:Betriebsanleitung der Hubarbeitsbühne ist auf der Baustelle vorhanden#B 212';
m[x++]='06:Beim Aufrichten/ Rückbau von Holzkonstruktionen geeignete Hilfskonstruktionen vorsehen#C 362';
m[x++]='07:Vor Montage von Bauteilen: schriftliche Montageanweisung für die Baustelle#';
m[x++]='08:Montagearbeiten: nur Lastaufnahmemittel verwenden, die nach Montageanweisung vorgesehenen sind#';
m[x++]='09:Bauteillagerung auf tragfähigem Untergrund mit kippsicherer Aufstellung#';
m[x++]='10:Bei Traggerüsten: für serienmäßig hergestellte Gerüstbauteile Aufbau- und Verwendungsanleitung beachten#';
m[x++]='11:Schriftliche Montageanweisung für Traggerüste und Schalungen: Gewicht, Lage der Anschlagpunkte (Transportlage beachten), Reihenfolge der Montage, Hilfskonstruktionen (z. B. Abspannungen, Aussteifungen)#';
m[x++]='12:Abböschen von Baugruben und Gräben nach DIN 4124: 45&deg; bei nicht bindigen Böden, 60&deg; bei bindigen Böden, 80&deg; bei Fels#C 469';
m[x++]='13:Standsicherheitsnachweis für Abböschungen, die von den Böschungswinkeln nach DIN 4124 abweichen und Gruben- und Grabentiefen über 5,0 m#C 469';
m[x++]='14:Lastfreien Schutzstreifen (60 cm breit) beidseitig anordnen und von Hindernissen freihalten#C 469';
m[x++]='15:Unterfangungsarbeiten nach DIN 4123#C 468';
m[x++]='16:Labile Bauteile vorab entfernen und Schuttmassen regelmäßig abräumen#';
m[x++]='17:Beim Aufstellen von Großgeräten Tragfähigkeit, Ebenheit und Neigung des Untergrund beachten#';
m[x++]='18:Werkzeuge und längenorientierte Einbauteile mechanisch führen#';
m[x++]='19:Betreten von Brunnen, Bohrungen, Schächten nur wenn Standsicherheitsnachweis geführt ist.#';
m[x++]='20:Maschinen durch Anfahrschwelle u.ä. von Absturzkanten fernhalten.#';
m[x++]='21:Statik beim Rückbau tragender Teile beachten#C 301';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_elektr-strom1']=z;
datum[z]='180216';
titel[z]='Gefährdung durch elektrischen Strom';
gefahr[z]='Gefährdungsfaktoren: Elektrischer Strom';
fragen[z]='Welche Maßnahmen werden gegen Gefährdung durch elektrischen Strom getroffen?';
m[x++]='00:Errichten/Instandsetzen von elektrischen Anlagen und Betriebsmitteln wird durch Elektrofachkräfte durchgeführt#B 171,B 172';
m[x++]='01:Einsatz von besonderen Speisepunkten, bauartgeprüften Leitungen, Leuchten und Installationsmaterialien#B 171,B 172';
m[x++]='02:Einsatz von besonderen Speisepunkten, auch für Maschinen mit Frequenzumrichter, bauartgeprüften Leitungen, Leuchten und Installationsmaterialien#B 171,B 172';
m[x++]='03:Einsatz von besonderen Speisepunkten/Baustromverteilern (auch geeignet für Hochfrequenzmotoren), bauartgeprüften Leitungen, Leuchten und Installationsmaterialien#B 171,B 172';
m[x++]='04:Auf Freileitungen achten#C 412';
m[x++]='05:Besondere Schutzmaßnahmen in engen Räumen#C 411';
m[x++]='06:Besondere Schutzmaßnahmen in engen Räumen, auch Einsatz druckluftbetriebener Arbeitsmittel#C 411';
m[x++]='07:Auf Spannungsfreiheit von Leitungen im Arbeitsbereich achten, auch rückseitig#C 365';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_gefahrstoffe1']=z;
datum[z]='180216';
titel[z]='Gefährdung durch Gefahrstoffe';
gefahr[z]='Gefährdungsfaktoren: Gefahrstoffe';
fragen[z]='Wurde festgestellt, ob am Arbeitsplatz/in der Arbeitsstätte <a href="'+xpath+'ga_bau/f_g/g6002.htm">Gefahrstoffe</a> verwendet, entstehen oder freigesetzt werden können?';
m[x++]='00:Ermitteln, ob Gefahrstoffe verwendet, entstehen oder freigesetzt werden (zum Beispiel Sicherheitsdatenblatt)#A 042,D 504';
m[x++]='01:Ermitteln, in welchem Ausmaß, welcher Art und Dauer Gefahrstoffe verwendet werden (Arbeitsverfahren berücksichtigen)#A 042,D 504';
m[x++]='02:Staubvermeidung: staubarme Bearbeitungsverfahren (zum Beispiel Nassbearbeitung)#D 502,C 317';
m[x++]='03:Staubvermeidung: staubarme Bearbeitungsverfahren, Spülwasser regelmäßig wechseln#D 502';
m[x++]='04:Staubvermeidung: staubarme Bearbeitungsverfahren (zum Beispiel langsam laufende Trennwerkzeuge, "Knabberzangen")#C 302';
m[x++]='05:Staubabsaugung beim Trockenschneiden/ -bohren/ -schleifen#C 317';
m[x++]='06:Beim Entfernen von alten mit Holzschutzmitteln belasteten Holzkonstruktionen vorhandene Gefahrstoffe durch fachkundige Person ermitteln und angepasstes Arbeitsverfahren verwenden#C 313';
m[x++]='07:Beim Ausbau von alten KMF-Produkten staubarme Reinigung/ Folienabdeckung bei mangelnder Reinigungsmöglichkeit#C 320';
m[x++]='08:Staubniederschlagung durch Sprühnebel (Verbot von trockenem Kehren oder Abblasen mit Druckluft)#D 502';
m[x++]='09:Krebserzeugenden Holzstaub mit geeigneten Staubsaugern absaugen#C 315';
m[x++]='10:Hautschutz beim Umgang mit Beton, Mörtel und Putz gemäß Hautschutzplan#E 605';
m[x++]='11:Zeitanteil an Feuchtarbeit gering halten, sonst  besondere Schutzmaßnahmen ergreifen#E 605';
m[x++]='12:In Räumen unter Erdgleiche / untertägigen Räumen Belüftung für Sauerstoffgehalt &gt; 19 Vol.-%, Atemschutz bei toxischen Gasen#C 475,C 462,C 463';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_laerm1']=z;
datum[z]='180216';
titel[z]='Gefährdung durch Lärm';
gefahr[z]='Gefährdungsfaktoren: Lärm';
fragen[z]='Welche Maßnahmen werden bei <a href="'+xpath+'ga_bau/f_l/l7007.htm">lärmintensiven</a> Arbeiten getroffen?';
m[x++]='00:Lärmarme Maschinen und Werkzeuge#D 500,A 030';
m[x++]='01:Geeigneter Gehörschutz#E 609';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_brand-explosion1']=z;
datum[z]='180216';
titel[z]='Gefährdung durch Brand und Explosion';
gefahr[z]='Gefährdungsfaktoren: Brand und Explosion';
fragen[z]='Welche Maßnahmen werden getroffen bei Arbeiten mit Brandgefährdung (u. a. Trennschleifen, Umgang mit Flüssiggas), durch entzündliche/brandfördernde Stoffe (zum Beispiel Isolierstoffe, Dachpappe oder Kunststoffe) oder gegen das Entstehen von <a href="'+xpath+'ga_bau/f_bue/bue9054.htm">entzündlichen Gas-/Luftgemischen</a>?';
m[x++]='00:Besondere Bedingungen beim Einsatz von Heißluftpistolen/ Flüssiggasbrennern/ Heizgeräten beachten#C 231,C 232,B 186,C 234';
m[x++]='01:Maßnahmen nach Angaben des Betreibers beachten - nach Explosionsschutzdokument#';
m[x++]='02:Lösemitteldämpfe vermeiden#C 404,C 332';
m[x++]='03:Belüftung in Räumen unter Erdgleiche / untertägigen Räumen zur Verhinderung explosionsfähiger Atmosphären#C 475,C 462,C 463';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_elektromagn-feld1']=z;
datum[z]='180216';
titel[z]='Arbeiten unter Einwirkung elektromagnetischer Felder';
gefahr[z]='Gefährdungsfaktoren: Elektromagnetische Felder#C 413';
fragen[z]='Welche Maßnahmen werden getroffen bei Einwirkung <a href="'+xpath+'ga_bau/f_s/s13101.htm">elektromagnetischer Felder</a> (z. B. bei Arbeiten in der Nähe von Antennen, Transformatoren, Induktionsöfen)?';
m[x++]='00:Notwendige Abstände zu Antennenanlagen entsprechend der Standortbescheinigung einhalten oder beim Betreiber Informationen einholen.#C 413';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_biolog-stoffe1']=z;
datum[z]='180216';
titel[z]=' Gefährdung durch biologische Stoffe';
gefahr[z]='Gefährdungsfaktoren: Biologische Arbeitsstoffe# 503';
fragen[z]='Welche Maßnahmen werden beim Entfernen von Schimmelpilzen und <a href="'+xpath+'dguv/201_031/titel.htm">Taubenkot</a> ergriffen?';
m[x++]='00:Die Höhe der Belastung durch Schimmelpilze bzw. Taubenkot ist ermittelt.#C 324';
m[x++]='01:Allgemeine Hygienemaßnahmen beachten#';
m[x++]='02:Allgemeine Hygienemaßnahmen beachten bei Kontakt zu Abwasser, Schimmelpilzen#';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_phys-belastung1']=z;
datum[z]='180216';
titel[z]='Gefährdung durch physische Belastung / Arbeitsschweren#D 512, D 507';
gefahr[z]='Gefährdungsfaktoren: Körperliche Überlastung';
fragen[z]='Welche Maßnahmen werden getroffen, um <a href="'+xpath+'ga_bau/f_ku/ku8003.htm">körperliche Überlastung</a> durch <a href="'+xpath+'ga_bau/f_ku/ku80051.htm">häufiges Heben und Halten</a> schwerer Lasten oder Arbeiten in <a href="'+xpath+'ga_bau/f_ku/ku80095.htm">Zwangshaltung</a> zu verhindern?';
m[x++]='00:Lastgewichte werden reduziert.#D 506';
m[x++]='01:Es werden Maschinen und Geräte sowie ergonomische Hilfsmittel eingesetzt.#D 514';
m[x++]='02:Arbeitsplätze sind so eingerichtet, dass Zwangshaltungen und ungünstige Arbeitshöhen vermieden werden.#D 506';
m[x++]='03:Transportwege sind kurz, geliefert wird nahe am Einbauort.#D 514';
m[x++]='04:Es findet ein regelmäßiger Tätigkeitswechsel statt, um die Belastungsdauer zu minimieren.#D 506';
m[x++]='05:Trainierende Aktivitäten (Rückenschule, Ausgleichssport) werden gefördert.#D 506,D 507';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_psych-belastung1']=z;
datum[z]='160522';
titel[z]='Gefährdung durch psychische Belastung';
gefahr[z]='Gefährdungsfaktoren: Psychische Belastung';
fragen[z]='Welche Maßnahmen werden getroffen, damit die Beschäftigten ihre Leistungen möglichst motiviert und frei von psychischen Belastungen einbringen können?';
m[x++]='00:Die Arbeitsaufträge sind in der geplanten Zeit (mit der entsprechenden Pausenregelung) gut zu bewältigen.#D 508';
m[x++]='01:Die Arbeitsaufträge sind in der geplanten Zeit (mit der entsprechenden Pausenregelung) gut zu bewältigen.#D 508';
m[x++]='02:Es ist ausreichend Zeit für Absprachen und Klärung von offenen Fragen.#D 508';
m[x++]='03:Es ist ausreichend Zeit für Absprachen und Klärung von offenen Fragen.#D 508';
m[x++]='04:Fehler und Probleme werden als Möglichkeit genutzt um die Abläufe zu verbessern.#D 508';
m[x++]='05:Fehler und Probleme werden als Möglichkeit genutzt um die Abläufe zu verbessern.#D 508';
m[x++]='06:Die Arbeitszeiten und Bedingungen erlauben den Mitarbeitern sich in der Freizeit ausreichend zu erholen.#D 511';
m[x++]='07:Die Arbeitszeiten und Bedingungen erlauben den Mitarbeitern sich in der Freizeit ausreichend zu erholen.#D 511';
m[x++]='08:Für nicht absehbare Situationen gibt es einen Notfallplan.#D 508,A 004';
m[x++]='09:Für nicht absehbare Situationen gibt es einen Notfallplan.#D 508,A 004';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';
m=new Array();x=0;
ga_dateien['k_fahrz-oeff-verkehr1']=z;
datum[z]='180216';
titel[z]='Einsatz von Fahrzeugen im öffentlichen Verkehr';
gefahr[z]='Gefährdungsfaktoren: Unkontrolliert bewegte Teile; Stolpern, Rutschen, Stürzen';
fragen[z]='Welche Maßnahmen werden gegen die Gefährdungen durch Mängel beim Einsatz von <a href="'+xpath+'ga_bau/f_eg/eg11005.htm">Fahrzeugen</a> ergriffen?';
m[x++]='00:Geeignete Fahrzeugführer einsetzen (richtige Führerscheinklasse nach Fahrerlaubnis-Verordnung - FeV).#A 067';
m[x++]='01:Lenk-, Steuer-, Ruhezeiten beachten, vorherige Arbeitszeit berücksichtigen.#A 067';
m[x++]='02:Nur Fahrzeuge einsetzen, die technisch in Ordnung sind, z.B. (Winter-) Bereifung und deren Prüffrist nicht abgelaufen ist (z.B. Hauptuntersuchung).#A 067';
m[x++]='03:Hilfsmittel für Notfälle sind komplett vorhanden (Warnweste, Warndreieck, Verbandskasten).#A 067';
m[x++]='04:Tägliche Sicht- und Funktionsprüfung.#A 067';
m[x++]='05:Zulässiges Gesamtgewicht einhalten.#A 070';
m[x++]='06:Ladungssicherung#A 070';
m[x++]='90:';
massnahmen[z++]=m;
//------------------------------------------------------';





/* */

//blanko-Faktor
m=new Array();x=0;
ga_dateien['f_blanko']=z;
datum[z]='';
titel[z]='xxx';
gefahr[z]='Gefährdungen: ';
fragen[z]='xxx';
m[x++]='00:';
m[x++]='01:';
m[x++]='02:';
m[x++]='03:';
m[x++]='04:';
m[x++]='05:';
massnahmen[z++]=m;
