ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhaltsverzeichnis",
"hinw.htm	#Hinweis",
"vor.htm	#Vorbemerkung",
"1.htm	#1 Anwendungsbereich",
"2.htm	#2 Begriffsbestimmungen",
"3.htm	#3 Grundsätzliches",
"4.htm	#4 Systeme der persönlichen Schutzausrüstungen gegen Absturz",
"5.htm	#5 Beispiele für persönliche Schutzausrüstungen gegen Absturz",
"6.htm	#6 Gefährdungsbeurteilung",
"7.htm	#7 Auswahl",
"8.htm	#8 Benutzung",
"9.htm	#9 Betriebsanweisung, Unterweisung",
"10.htm	#10 Ordnungsgemäßer Zustand",
"anh1.htm	#Anhang 1",
"anh2.htm	#Anhang 2",
"anh3.htm	#Anhang 3",
"anh4.htm	#Anhang 4"
);