[Symbol]
WindowX=582
WindowY=390
Pictures=bilder\
AboutText=Wir danken der Firma Kroschke sign international GmbH für Ihre Unterstützung.

; Ab hier fängt die Deklaration der verschiedenen
; Sicherheitssymbole und ihrer Unterteilung an.
[Hauptgruppen]
1=Verbotszeichen
2=Warnzeichen
3=Gebotszeichen
4=Rettungszeichen
5=Brandschutzzeichen
6=Gefahrensymbole
7=GHS Symbole

[Gefahrensymbole]
1=E, Explosionsgefährlich, G01.WMF
2=O, Brandfördernd, G02.WMF
3=F+, Hochentzündlich, G03.WMF
4=F, Leichtentzündlich, G04.WMF
5=T+, Sehr giftig, G05.WMF
6=T, Giftig, G06.WMF
7=C, Ätzend, G07.WMF
8=Xi, Reizend, G08.WMF
9=Xn, Gesundheitsschädlich, G09.WMF
10=N, Umweltgefährlich, G10.WMF
11=E Text, Explosionsgefährlich mit Text, G01T.WMF
12=O Text, Brandfördernd mit Text, G02T.WMF
13=F+ Text, Hochentzündlich mit Text, G03T.WMF
14=F Text, Leichtentzündlich mit Text, G04T.WMF
15=T+ Text, Sehr giftig mit Text, G05T.WMF
16=T Text, Giftig mit Text, G06T.WMF
17=C Text, Ätzend mit Text, G07T.WMF
18=Xi Text, Reizend mit Text, G08T.WMF
19=Xn Text, Gesundheitsschädlich mit Text, G09T.WMF
20=N Text, Umweltgefährlich mt Text, G10T.WMF

[Verbotszeichen]
1=P001, Allgemeines Verbotszeichen (Dieses Zeichen darf nur in Verbindung mit einem Zusatzzeichen angewendet werden, das das Verbot konkretisiert), p001.wmf
2=P002, Rauchen verboten, p002.wmf
3=P003, Keine offene Flamme; Feuer, offene Zündquelle und Rauchen verboten, p003.wmf
4=P004, Für Fußgänger verboten, p004.wmf
5=P005, Kein Trinkwasser, p005.wmf
6=P006, Für Flurförderzeuge verboten, p006.wmf
7=P007, Kein Zutritt für Personen mit Herzschrittmachern oder implantierten Defibrillatoren (Das Verbot gilt auch für sonstige aktive Implantate), p007.wmf
8=P010, Berühren verboten, p010.wmf
9=P011, Mit Wasser löschen verboten, p011.wmf
10=P012, Keine schwere Last, p012.wmf
11=P013, Eingeschaltete Mobiltelefone verboten, p013.wmf
12=P014, Kein Zutritt für Personen mit Implantaten aus Metall, p014.wmf
13=P015, Hineinfassen verboten, p015.wmf
14=P020, Aufzug im Brandfall nicht benutzen, p020.wmf
15=P021, Mitführen von Hunden verboten (Das Verbot gilt auch für andere Tiere), p021.wmf
16=P022, Essen und Trinken verboten, p022.wmf
17=P023, Abstellen oder Lagern verboten, p023.wmf
18=P024, Betreten der Fläche verboten, p024.wmf
19=P027, Personenbeförderung verboten, p027.wmf
20=P028, Benutzen von Handschuhen verboten, p028.wmf
21=P031, Schalten verboten, p031.wmf
22=D-P006, Zutritt für Unbefugte verboten (aus DIN 4844-2 "Graphische Symbole - Sicherheitsfarben und Sicherheitszeichen" Ausgabe Dezember 2012), p006_d.wmf
23=P016, Mit Wasser spritzen verboten (aus DIN 4844-2 "Graphische Symbole - Sicherheitsfarben und Sicherheitszeichen" Ausgabe Dezember 2012), p016.wmf
24=D-P022, Besteigen für Unbefugte verboten (aus DIN 4844-2 "Graphische Symbole - Sicherheitsfarben und Sicherheitszeichen" Ausgabe Dezember 2012), p022_d.wmf
25=WSP001, Laufen verboten (aus DIN 4844-2 "Graphische Symbole - Sicherheitsfarben und Sicherheitszeichen" Ausgabe Dezember 2012), wsp001.wmf



[Warnzeichen]
1=W001, Allgemeines Warnzeichen (Dieses Zeichen darf nur in Verbindung mit einem Zusatzzeichen angewendet werden, das die Gefahr konkretisiert), w001.wmf
2=W002, Warnung vor explosionsgefährlichen Stoffen, w002.wmf
3=W003, Warnung vor radioaktiven Stoffen oder ionisierender Strahlung, w003.wmf
4=W004, Warnung vor Laserstrahl, w004.wmf
5=W005, Warnung vor nicht ionisierender Strahlung, w005.wmf
6=W006, Warnung vor magnetischem Feld, w006.wmf
7=W007, Warnung vor Hindernissen am Boden, w007.wmf
8=W008, Warnung vor Absturzgefahr, w008.wmf
9=W009, Warnung vor Biogefährdung, w009.wmf
10=W010, Warnung vor niedriger Temperatur/Frost, w010.wmf
11=W011, Warnung vor Rutschgefahr, w011.wmf
12=W012, Warnung vor elektrischer Spannung, w012.wmf
13=W014, Warnung vor Flurförderzeugen, w014.wmf
14=W015, Warnung vor schwebender Last, w015.wmf
15=W016, Warnung vor giftigen Stoffen, w016.wmf
16=W017, Warnung vor heißer Oberfläche, w017.wmf
17=W018, Warnung vor automatischem Anlauf, w018.wmf
18=W019, Warnung vor Quetschgefahr, w019.wmf
19=W021, Warnung vor feuergefährlichen Stoffen, w021.wmf
20=W023, Warnung vor ätzenden Stoffen, w023.wmf
21=W024, Warnung vor Handverletzungen, w024.wmf
22=W025, Warnung vor gegenläufigen Rollen (Die Warnung gilt auch für Einzugsgefahren anderer Art), w025.wmf
23=W026, Warnung vor Gefahren durch das Aufladen von Batterien, w026.wmf
24=W027, Warnung vor optischer Strahlung, w027.wmf
25=W028, Warnung vor brandfördernden Stoffen, w028.wmf
26=W029, Warnung vor Gasflaschen, w029.wmf
27=D-W021, Warnung vor explosionsfähiger Atmosphäre (aus DIN 4844-2 "Graphische Symbole - Sicherheitsfarben und Sicherheitszeichen" Ausgabe Dezember 2012), d-w021.wmf

[Gebotszeichen]
1=M001, Allgemeines Gebotszeichen (Dieses Zeichen darf nur in Verbindung mit einem Zusatzzeichen angewendet werden, welches das Gebot konkretisiert), m001.wmf
2=M003, Gehörschutz benutzen, m003.wmf
3=M004, Augenschutz benutzen, m004.wmf
4=M008, Fußschutz benutzen, m008.wmf
5=M009, Handschutz benutzen, m009.wmf
6=M010, Schutzkleidung benutzen, m010.wmf
7=M011, Hände waschen, m011.wmf
8=M012, Handlauf benutzen, m012.wmf
9=M013, Gesichtsschutz benutzen, m013.wmf
10=M014, Kopfschutz benutzen, m014.wmf
11=M015, Warnweste benutzen, m015.wmf
12=M016, Maske benutzen, m016.wmf
13=M017, Atemschutz benutzen, m017.wmf
14=M018, Auffanggurt benutzen, m018.wmf
15=M020, Rückhaltesystem benutzen, m020.wmf
16=M021, Vor Wartung oder Reparatur freischalten, m021.wmf
17=M022, Hautschutzmittel benutzen, m022.wmf
18=M023, Übergang benutzen, m023.wmf
19=M024, Fußgängerweg benutzen, m024.wmf
20=M026, Schutzschürze benutzen, m026.wmf
21=WSM001, Rettungsweste benutzen (aus DIN 4844-2 "Graphische Symbole - Sicherheitsfarben und Sicherheitszeichen" - Ausgabe Dezember 2012), wsm001.wmf



[Rettungszeichen]
1=E001, Rettungsweg/Notausgang (links) (Dieses Rettungszeichen darf nur in Verbindung mit einem Zusatzzeichen [Richtungspfeil] verwendet werden), e001.wmf
2=E002, Rettungsweg/Notausgang (rechts) (Dieses Rettungszeichen darf nur in Verbindung mit einem Zusatzzeichen [Richtungspfeil] verwendet werden), e002.wmf
3=E003, Erste Hilfe, e003.wmf
4=E004, Notruftelefon, e004.wmf
5=E007, Sammelstelle, e007.wmf
6=E009, Arzt, e009.wmf
7=E010, Automatisierter Externer Defibrillator (AED), e010.wmf
8=E011, Augenspüleinrichtung, e011.wmf
9=E012, Notdusche, e012.wmf
10=E013, Krankentrage, e013.wmf
11=E016, Notausstieg mit Fluchtleiter, e016.wmf
12=E017, Rettungsausstieg, e017.wmf
13=WSE001, Öffentliche Rettungsausrüstung (aus DIN 4844-2 "Graphische Symbole - Sicherheitsfarben und Sicherheitszeichen" Ausgabe Dezember 2012), wse001.wmf
14=D-E019, Notausstieg (aus DIN 4844-2 "Graphische Symbole - Sicherheitsfarben und Sicherheitszeichen" Ausgabe Dezember 2012), e019_d.wmf
15=Beispiel für Rettungsweg/Notausgang (E002) mit Zusatzzeichen (Richtungspfeil), e002_u.wmf
16=Beispiel für Rettungsweg/Notausgang (E002) mit Zusatzzeichen (Richtungspfeil), e002_r.wmf


[Brandschutzzeichen]
1=F001, Feuerlöscher, f001.wmf
2=F002, Löschschlauch, f002.wmf
3=F003, Feuerleiter, f003.wmf
4=F004, Mittel und Geräte zur Brandbekämpfung, f004.wmf
5=F005, Brandmelder, f005.wmf
6=F006, Brandmeldetelefon, f006.wmf


[GHS Symbole]
1=GHS01, explodierende Bombe, explos.WMF
2=GHS02, Flamme, flamme.WMF
3=GHS03, Flamme über einem Kreis, rondflam.WMF
4=GHS04, Gasflasche, bottle.WMF
5=GHS05, Ätzwirkung, acid.WMF
6=GHS06, Totenkopf mit gekreuzten Knochen, scull.WMF
7=GHS07, Ausrufezeichen , exclam.WMF
8=GHS08, Gesundheitsgefahr, silhouet.WMF
9=GHS09, Umwelt, pollut.WMF




