[Setup]
Text1=Willkommen zur Installation von "Gefährdungsbeurteilungen BG BAU".
Text2=Das Programm wird in das folgende Verzeichnis kopiert: (%d,%d MB frei)
Text3=Teilinstallation ohne Vorschriften (%d,%d MB, ca. 1-5 Minuten)
Text4=Vollinstallation (%d,%d MB, ca. 7-20 Minuten)
pfadkurz=GB_BGBAU
pfadlang=Gefährdungsbeurteilungen_BGBAU
prgname=Gefährdungsbeurteilungen BG BAU
makeini=Teilinst
ie_min_version=5
MakeShortcut=1

;Icons für Programmmanager/Startmenü
Group=Gefährdungsbeurteilungen BG BAU
Icon1=Uninstall
CmdLine1=~\uninst.exe
Icon2=Gefährdungsbeurteilungen BG BAU
CmdLine2=~\win\show8.exe
Extension2=.ga1
ExtensionDescr2=ga1-Datei
FileDescr2=Gefährdungsbeurteilung BG BAU
Icon3=Sicherheitszeichen
CmdLine3=~\win\symbol.exe

;fuer uninstall (registry)
uninst1=-Software\Microsoft\Windows\CurrentVersion\Uninstall
uninst2=Gefährdungsbeurteilungen BG BAU
uninst3=-HKEY_CLASSES_ROOT\
uninst4=.ga1
uninst5=-HKEY_CLASSES_ROOT\ga1-Datei\Shell\Open\
uninst6=Command
uninst7=-HKEY_CLASSES_ROOT\ga1-Datei\Shell\
uninst8=Open
uninst9=-HKEY_CLASSES_ROOT\ga1-Datei\
uninst10=Shell
uninst11=-HKEY_CLASSES_ROOT\ga1-Datei\
uninst12=DefaultIcon
uninst13=-HKEY_CLASSES_ROOT\
uninst14=ga1-Datei

[Fileset0]
;Zu kopierende Dateinamen. *.* ist erlaubt
Filenames=win\*.*;uninst.exe;daten\daten.*;daten\button*.js;daten\images\*.*;daten\struktur*.js;daten\pfade.js;daten\daten.css;daten\font*.css;daten\grid.js;daten\gv.css;daten\index.htm;daten\gabau-2;daten\ga\*.*;daten\ga_kurzhh\*.*;daten\ga_bau\*.*;daten\grafik\*.*;daten\help\*.*;daten\index\*.*;daten\infopool\*.*;daten\inhalt_ga_cd\*.*;daten\logos\*.*;daten\mask1024\*.*;daten\pics1024\*.*

Summe der Dateigrößen bei den verschiedenen Clustergrößen
;(werden von count.exe berechnet)
FileSize512=235679744
FileSize1024=236631040
FileSize2048=238182400
FileSize4096=242843648
FileSize8192=253018112
FileSize16384=274219008
FileSize32768=317030400
Filesize65536=406192128

[Fileset1]
;optionale Dateien
Filenames=daten\bau\*.*;daten\bausteine\*.*;daten\gv\*.*;daten\pdf\*.*;daten\statistik\*.*;daten\tr\*.*;daten\dguv\*.*
FileSize512=606447104
FileSize1024=610292736
FileSize2048=617478144
FileSize4096=634007552
FileSize8192=673718272
FileSize16384=762626048
FileSize32768=952532992
Filesize65536=1354366976
