ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"vorbem.htm	#Vorbemerkung",
"1.htm	#1 Anwendungsbereich",
"2.htm	#2 Begriffsbestimmungen",
"3.htm	#3 Grundsätzliches",
"4.htm	#4 Arten von Gehörschutz",
"5.htm	#5 Gefährdungsbeurteilung",
"6.htm	#6 Auswahl",
"7.htm	#7 Benutzung",
"8.htm	#8 Individuell angepasste Gehörschützer",
"9.htm	#9 Betriebsanweisung und Unterweisung",
"10.htm	#10 Ordnungsgemäßer Zustand",
"11.htm	#11 Gehörschutznutzung in Bereichen mit LEX,8h &le; 80 dB(A)",
"anh1.htm	#Anhang 1 Rechnerisches Verfahren zur Prüfung auf Einhaltung der MZE",
"anh2.htm	#Anhang 2 Methoden der Auswahl von geeignetem Gehörschutz",
"anh3.htm	#Anhang 3 Ermittlung der Schallexposition für Gehörschützer mit sicherheitsrelevanter Kommunikation",
"anh4.htm	#Anhang 4 Anatomie von Außen- und Mittelohr",
"anh5.htm	#Anhang 5 Richtlinie zur Unterweisung mit praktischen Übungen",
"anh6.htm	#Anhang 6 Muster einer Betriebsanweisung Gehörschutz",
"anh7.htm	#Anhang 7 Muster einer EU-Konformitätserklärung",
"anh8.htm	#Anhang 8 Abkürzungsverzeichnis für schalltechnische Mess- und Beurteilungsgrößen",
"anh9.htm	#Anhang 9 Herstellungsschritte einer Gehörschutz-Otoplastik",
"anh10.htm	#Anhang 10 Vorschriften und Regeln",
"anh11.htm	#Anhang 11 Weiterführende Literatur",
"anh12.htm	#Anhang 12 Alle dem Institut für Arbeitsschutz gemeldeten Gehörschützer mit EU-Baumusterprüfbescheinigung"
);