ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"regeln.htm	#Regeln",
"vor.htm	#Vorbemerkung",
"1.htm	#1 Anwendungsbereich",
"2.htm	#2 Begriffsbestimmungen",
"3.htm	#3 Allgemeine Anforderungen",
"4.htm	#4 Informationsermittlung",
"5.htm	#5 Gef&auml;hrdungsbeurteilung",
"6.htm	#6 Schutzma&szlig;nahmen",
"7.htm	#7 Pr&uuml;fung und Pflege von wassergemischten K&uuml;hlschmierstoffen, Ansetzwasser, Pr&uuml;fplan",
"8.htm	#8 Entsorgung, Aufbereitung, Verwertung",
"9.htm	#9 Zeitpunkt der Anwendung",
"anh1.htm	#Anhang 1",
"anh2.htm	#Anhang 2",
"anh3.htm	#Anhang 3",
"anh4.htm	#Anhang 4",
"anh5.htm	#Anhang 5",
"anh6.htm	#Anhang 6",
"anh6a.htm	#Anhang 6a",
"anh7.htm	#Anhang 7",
"anh8.htm	#Anhang 8",
"anh9.htm	#Anhang 9",
"anh10.htm	#Anhang 10",
"anh10a.htm	#Anhang 10a",
"anh11.htm	#Anhang 11",
"anh12.htm	#Anhang 12",
"anh13.htm	#Anhang 13",
"anh14.htm	#Anhang 14",
"anh15.htm	#Anhang 15"
);