ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhaltsübersicht",
"1.htm	#§ 1 Zweck des Gesetzes",
"1a.htm	#§ 1a (weggefallen)",
"2.htm	#§ 2 Begriffsbestimmungen",
"3.htm	#§ 3 Prävention durch Aufklärung",
"4.htm	#§ 4 Aufgaben des Robert Koch-Institutes",
"5.htm	#§ 5 Epidemische Lage von nationaler Tragweite",
"5a.htm	#§ 5a Ausübung heilkundlicher Tätigkeiten bei Vorliegen einer epidemischen Lage vonnationaler Tragweite, Verordnungsermächtigung",
"5b.htm	#§ 5b Schutzmasken in der Nationalen Reserve Gesundheitsschutz",
"5c.htm	#§ 5c Verfahren bei ...",
"6.htm	#§ 6 Meldepflichtige Krankheiten",
"7.htm	#§ 7 Meldepflichtige Nachweise von Krankheitserregern",
"8.htm	#§ 8 Zur Meldung verpflichtete Personen",
"9.htm	#§ 9 Namentliche Meldung",
"10.htm	#§ 10 Nichtnamentliche Meldung",
"11.htm	#§ 11 Übermittlung an die zuständige Landesbehörde und an das Robert Koch-Institut",
"12.htm	#§ 12 Übermittlungen und Mitteilungen auf Grund völker- und unionsrechtlicher Vorschriften",
"12a.htm	#§ 12a (weggefallen)",
"13.htm	#§ 13 Weitere Formen der epidemiologischen Überwachung; Verordnungsermächtigung",
"14.htm	#§ 14 Elektronisches Melde- und Informationssystem; Verordnungsermächtigung",
"14a.htm	#§ 14a Interoperabilität; Verordnungsermächtigung",
"15.htm	#§ 15 Anpassung der Meldepflicht an die epidemische Lage",
"15a.htm	#§ 15a Durchführung der infektionshygienischen und hygienischen Überwachung",
"16.htm	#§ 16 Allgemeine Maßnahmen zur Verhütung übertragbarer Krankheiten",
"17.htm	#§ 17 Besondere Maßnahmen zur Verhütungübertragbarer Krankheiten, Verordnungs-ermächtigung",
"18.htm	#§ 18 Behördlich angeordnete Maßnahmen zur Desinfektion und zur Bekämpfung von Gesundheitsschädlingen, Krätzmilben und Kopfläusen; Verordnungsermächtigung",
"19.htm	#§ 19 Aufgaben des Gesundheitsamtes in besonderen Fällen",
"20.htm	#§ 20 Schutzimpfungen und andere Maßnahmen der spezifischen Prophylaxe",
"20a.htm	#§ 20a (weggefallen)",
"20b.htm	#§ 20b Durchführung von Schutzimpfungen gegen das Coronavirus SARS-CoV-2",
"20c.htm	#§ 20c Durchführung von Grippeschutzimpfungen und Schutzimpfungen gegen das Coronavirus SARS-CoV-2 durch Apotheker",
"21.htm	#§ 21 Impfstoffe",
"22.htm	#§ 22 Impf-, Genesenen- und Testdokumentation",
"22a.htm	#§ 22a Impf-, Genesenen- und Testnachweis bei COVID-19; COVID-19-Zertifikate; Verordnungsermächtigung",
"23.htm	#§ 23 Nosokomiale Infektionen; Resistenzen; Rechtsverordnungen durch die Länder",
"23a.htm	#§ 23a Personenbezogene Daten über den Impf- und Serostatus von Beschäftigten",
"24.htm	#§ 24 Feststellung und Heilbehandlung übertragbarer Krankheiten, Verordnungsermächtigung",
"25.htm	#§ 25 Ermittlungen",
"26.htm	#§ 26 Teilnahme des behandelnden Arztes",
"27.htm	#§ 27 Gegenseitige Unterrichtung",
"28.htm	#§ 28 Schutzmaßnahmen",
"28a.htm	#§ 28a Besondere Schutzmaßnahmen zur Verhinderung der Verbreitung der Coronavirus- Krankheit-2019 (COVID-19) bei epidemischer Lage von nationaler Tragweite",
"28b.htm	#§ 28b Besondere Schutzmaßnahmen zur Verhinderung der Verbreitung der Coronavirus- Krankheit-2019 ...",
"28c.htm	#§ 28c Verordnungsermächtigung für besondere Regelungen für Geimpfte, Getestete und vergleichbare Personen",
"29.htm	#§ 29 Beobachtung",
"30.htm	#§ 30 Absonderung",
"31.htm	#§ 31 Berufliches Tätigkeitsverbot",
"32.htm	#§ 32 Erlass von Rechtsverordnungen",
"33.htm	#§ 33 Gemeinschaftseinrichtungen",
"34.htm	#§ 34 Gesundheitliche Anforderungen, Mitwirkungspflichten, Aufgaben des Gesundheitsamtes",
"35.htm	#§ 35 Infektionsschutz in Einrichtungen und Unternehmen der Pflege und Eingliederungshilfe, Verordnungsermächtigung",
"36.htm	#§ 36 Infektionsschutz bei bestimmten Einrichtungen, Unternehmen und Personen; Verordnungsermächtigung",
"37.htm	#§ 37 Beschaffenheit von Wasser für den menschlichen Gebrauch sowie von Wasser zum Schwimmen oder Baden in Becken oder Teichen, Überwachung",
"38.htm	#§ 38 Verordnungsermächtigung",
"39.htm	#§ 39 Untersuchungen, Maßnahmen der zuständigen Behörde",
"40.htm	#§ 40 Aufgaben des Umweltbundesamtes",
"41.htm	#§ 41 Abwasser",
"42.htm	#§ 42 Tätigkeits-&nbsp;und Beschäftigungsverbote",
"43.htm	#§ 43 Belehrung, Bescheinigung des Gesundheitsamtes",
"44.htm	#§ 44 Erlaubnispflicht für Tätigkeiten mit Krankheitserregern",
"45.htm	#§ 45 Ausnahmen",
"46.htm	#§ 46 Tätigkeit unter Aufsicht",
"47.htm	#§ 47 Versagungsgründe, Voraussetzungen für die Erlaubnis",
"48.htm	#§ 48 Rücknahme und Widerruf",
"49.htm	#§ 49 Anzeigepflichten",
"50.htm	#§ 50 Veränderungsanzeige",
"50a.htm	#§ 50a Laborcontainment und Ausrottung des Poliovirus; Verordnungsermächtigung ",
"51.htm	#§ 51 Aufsicht",
"52.htm	#§ 52 Abgabe",
"53.htm	#§ 53 Anforderungen an Räume und Einrichtungen, Gefahrenvorsorge",
"53a.htm	#§ 53a Verfahren über eine einheitliche Stelle, Entscheidungsfrist",
"54.htm	#§ 54 Vollzug durch die Länder",
"54a.htm	#§ 54a Vollzug durch die Bundeswehr",
"54b.htm	#§ 54b Vollzug urch das Eisenbahn-Bundesamt",
"55.htm	#§ 55 Angleichung an Gemeinschaftsrecht",
"56.htm	#§ 56 Entschädigung",
"57.htm	#§ 57 Verhältnis zur Sozialversicherung und zur Arbeitsförderung",
"58.htm	#§ 58 Aufwendungserstattung",
"59.htm	#§ 59 Arbeits- und sozialrechtliche Sondervorschriften",
"60.htm	#§ 60 (weggefallen)",
"61.htm	#§ 61 (weggefallen)",
"62.htm	#§ 62 (weggefallen)",
"63.htm	#§ 63 (weggefallen)",
"64.htm	#§ 64 (weggefallen)",
"65.htm	#§ 65 Entschädigung bei behördlichen Maßnahmen",
"66.htm	#§ 66 Zahlungsverpflichteter",
"67.htm	#§ 67 Pfändung",
"68.htm	#§ 68 Rechtsweg",
"69.htm	#§ 69 Kosten",
"70.htm	#§ 70 (weggefallen)",
"71.htm	#§ 71 (weggefallen)",
"72.htm	#§ 72 (weggefallen)",
"73.htm	#§ 73 Bußgeldvorschriften",
"74.htm	#§ 74 Strafvorschriften",
"75.htm	#§ 75 Weitere Strafvorschriften",
"75a.htm	#§ 75a Weitere Strafvorschriften",
"76.htm	#§ 76 Einziehung",
"77.htm	#§ 77 Übergangsvorschriften",
"anl.htm	#Anlage (zu § 5b Absatz 4)"
);