ord=new Array(
"titel.htm	#Titelseite",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Anwendungs- und Geltungsbereich",
"2.htm	#§ 2 Exposition; Expositionssituationen; Expositionskategorien",
"3.htm	#§ 3 Begriff der radioaktiven Stoffe",
"4.htm	#§ 4 Tätigkeiten, Tätigkeitsarten",
"5.htm	#§ 5 Sonstige Begriffsbestimmungen",
"6.htm	#§ 6 Rechtfertigung von Tätigkeitsarten; Verordnungsermächtigung",
"7.htm	#§ 7 Verfahren zur Prüfung der Rechtfertigung einer Tätigkeitsart; Verordnungsermächtigung",
"8.htm	#§ 8 Vermeidung unnötiger Exposition und Dosisreduzierung",
"9.htm	#§ 9 Dosisbegrenzung",
"10.htm	#§ 10 Genehmigungsbedürftige Errichtung von Anlagen zur Erzeugung ionisierender Strahlung",
"11.htm	#§ 11 Voraussetzungen für die Erteilung der Genehmigung; Aussetzung des Genehmigungsverfahrens",
"12.htm	#§ 12 Genehmigungsbedürftige Tätigkeiten",
"13.htm	#§ 13 Allgemeine Voraussetzungen für die Erteilung der Genehmigung; Aussetzung des Genehmigungsverfahrens",
"14.htm	#§ 14 Besondere Voraussetzungen bei Tätigkeiten im Zusammenhang mit der Anwendung am Menschen",
"15.htm	#§ 15 Besondere Voraussetzungen bei Tätigkeiten im Zusammenhang mit der Anwendung am Tier in der Tierheilkunde",
"16.htm	#§ 16 Erforderliche Unterlagen",
"17.htm	#§ 17 Anzeigebedürftiger Betrieb von Anlagen zur Erzeugung ionisierender Strahlung",
"18.htm	#§ 18 Prüfung des angezeigten Betriebs einer Anlage zur Erzeugung ionisierender Strahlung",
"19.htm	#§ 19 Genehmigungs- und anzeigebedürftiger Betrieb von Röntgeneinrichtungen",
"20.htm	#§ 20 Prüfung des angezeigten Betriebs einer Röntgeneinrichtung",
"21.htm	#§ 21 Beendigung des genehmigten oder angezeigten Betriebs oder Umgangs",
"22.htm	#§ 22 Anzeigebedürftige Prüfung, Erprobung, Wartung und Instandsetzung von Röntgeneinrichtungen oder Störstrahlern",
"23.htm	#§ 23 Verhältnis zur Verordnung (EU) 2017/745",
"24.htm	#§ 24 Verordnungsermächtigungen",
"25.htm	#§ 25 Genehmigungsbedürftige Beschäftigung in fremden Anlagen oder Einrichtungen",
"26.htm	#§ 26 Anzeigebedürftige Beschäftigung im Zusammenhang mit dem Betrieb fremder Röntgeneinrichtungen oder Störstrahler",
"27.htm	#§ 27 Genehmigungsbedürftige Beförderung sonstiger radioaktiver Stoffe",
"28.htm	#§ 28 Genehmigungsfreie Beförderung",
"29.htm	#§ 29 Voraussetzungen für die Erteilung der Genehmigung",
"30.htm	#§ 30 Verordnungsermächtigung für die grenzüberschreitende Verbringung radioaktiver Stoffe",
"31.htm	#§ 31 Genehmigungsbedürftige Anwendung radioaktiver Stoffe oder ionisierender Strahlung am Menschen zum Zweck der medizinischen Forschung",
"32.htm	#§ 32 Anzeigebedürftige Anwendung radioaktiver Stoffe oder ionisierender Strahlung am Menschen zum Zweck der medizinischen Forschung",
"33.htm	#§ 33 Prüfung der Anzeige durch die zuständige Behörde",
"34.htm	#§ 34 Untersagung der angezeigten Anwendung radioaktiver Stoffe oder ionisierender Strahlung am Menschen zum Zweck der medizinischen Forschung",
"35.htm	#§ 35 Deckungsvorsorge bei der anzeigebedürftigen Anwendung radioaktiver Stoffe oder ionisierender Strahlung am Menschen zum Zweck der medizinischen Forschung",
"36.htm	#§ 36 Ethikkommission",
"37.htm	#§ 37 Verordnungsermächtigung",
"38.htm	#§ 38 Rechtfertigung von Tätigkeitsarten mit Konsumgütern oder bauartzugelassenen Vorrichtungen; Verordnungsermächtigung",
"39.htm	#§ 39 Unzulässiger Zusatz radioaktiver Stoffe und unzulässige Aktivierung",
"40.htm	#§ 40 Genehmigungsbedürftiger Zusatz radioaktiver Stoffe und genehmigungsbedürftige Aktivierung",
"41.htm	#§ 41 Voraussetzungen für die Erteilung der Genehmigung des Zusatzes radioaktiver Stoffe oder der Aktivierung",
"42.htm	#§ 42 Genehmigungsbedürftige grenzüberschreitende Verbringung von Konsumgütern",
"43.htm	#§ 43 Voraussetzungen für die Erteilung der Genehmigung der grenzüberschreitenden Verbringung von Konsumgütern",
"44.htm	#§ 44 Rückführung von Konsumgütern",
"45.htm	#§ 45 Bauartzugelassene Vorrichtungen",
"46.htm	#§ 46 Verfahren der Bauartzulassung",
"47.htm	#§ 47 Zulassungsschein",
"48.htm	#§ 48 Verwendung oder Betrieb bauartzugelassener Vorrichtungen",
"49.htm	#§ 49 Verordnungsermächtigung",
"50.htm	#§ 50 Anzeigebedürftiger Betrieb von Luftfahrzeugen",
"51.htm	#§ 51 Prüfung des angezeigten Betriebs von Luftfahrzeugen",
"52.htm	#§ 52 Anzeigebedürftiger Betrieb von Raumfahrzeugen",
"53.htm	#§ 53 Prüfung des angezeigten Betriebs von Raumfahrzeugen",
"54.htm	#§ 54 Beendigung der angezeigten Tätigkeit",
"55.htm	#§ 55 Abschätzung der Exposition",
"56.htm	#§ 56 Anzeige",
"57.htm	#§ 57 Prüfung der angezeigten Tätigkeit",
"58.htm	#§ 58 Beendigung der angezeigten Tätigkeit",
"59.htm	#§ 59 Externe Tätigkeit",
"60.htm	#§ 60 Anfall, Verwertung oder Beseitigung von Rückständen",
"61.htm	#§ 61 Anfall und Lagerung überwachungsbedürftiger Rückstände; Verordnungsermächtigung",
"62.htm	#§ 62 Entlassung von Rückständen aus der Überwachung; Verordnungsermächtigung",
"63.htm	#§ 63 In der Überwachung verbleibende Rückstände; Verordnungsermächtigung",
"64.htm	#§ 64 Entfernung von Kontaminationen von Grundstücken",
"65.htm	#§ 65 Überwachung sonstiger Materialien; Verordnungsermächtigung",
"66.htm	#§ 66 Mitteilungspflichten zur Betriebsorganisation",
"67.htm	#§ 67 Ausnahme von dem Erfordernis der Genehmigung und der Anzeige",
"68.htm	#§ 68 Verordnungsermächtigung; Verwendungs- und Verwertungsverbot",
"69.htm	#§ 69 Strahlenschutzverantwortlicher",
"70.htm	#§ 70 Strahlenschutzbeauftragter",
"71.htm	#§ 71 Betriebliche Zusammenarbeit im Strahlenschutz",
"72.htm	#§ 72 Weitere Pflichten des Strahlenschutzverantwortlichen und des Strahlenschutzbeauftragten; Verordnungsermächtigung",
"73.htm	#§ 73 Verordnungsermächtigung für den Erlass einer Strahlenschutzanweisung",
"74.htm	#§ 74 Erforderliche Fachkunde und Kenntnisse im Strahlenschutz; Verordnungsermächtigungen",
"75.htm	#§ 75 Überprüfung der Zuverlässigkeit",
"76.htm	#§ 76 Verordnungsermächtigungen für die physikalische Strahlenschutzkontrolle und Strahlenschutzbereiche; Aufzeichnungs- und Mitteilungspflichten der Daten der Körperdosis",
"77.htm	#§ 77 Grenzwert für die Berufslebensdosis",
"78.htm	#§ 78 Grenzwerte für beruflich exponierte Personen",
"79.htm	#§ 79 Verordnungsermächtigung für die berufliche Exposition; Führung einer Gesundheitsakte",
"80.htm	#§ 80 Grenzwerte für die Exposition der Bevölkerung",
"81.htm	#§ 81 Verordnungsermächtigung für den Schutz der Bevölkerung und der Umwelt",
"82.htm	#§ 82 Verordnungsermächtigung für Pflichten des Strahlenschutzverantwortlichen im Zusammenhang mit Störfällen und Notfällen",
"83.htm	#§ 83 Anwendung ionisierender Strahlung oder radioaktiver Stoffe am Menschen",
"84.htm	#§ 84 Früherkennung; Verordnungsermächtigung",
"85.htm	#§ 85 Aufzeichnungs-, Aufbewahrungs- und behördliche Mitteilungspflichten von Daten und Bilddokumenten bei der Anwendung am Menschen; Verordnungsermächtigung",
"86.htm	#§ 86 Verordnungsermächtigungen zum Schutz von Personen bei der Anwendung ionisierender Strahlung oder radioaktiver Stoffe am Menschen",
"87.htm	#§ 87 Verordnungsermächtigungen zum Schutz von Personen bei der Anwendung radioaktiver Stoffe oder ionisierender Strahlung am Tier in der Tierheilkunde",
"88.htm	#§ 88 Register über hochradioaktive Strahlenquellen; Verordnungsermächtigungen",
"89.htm	#§ 89 Verordnungsermächtigungen zu der Sicherheit von Strahlungsquellen",
"90.htm	#§ 90 Verordnungsermächtigung für Pflichten, Aufgaben und Befugnisse bei Vorkommnissen; Aufzeichnungs-, Übermittlungs- und Aufbewahrungspflichten",
"91.htm	#§ 91 Verordnungsermächtigung für Informationspflichten des Herstellers oder Lieferanten von Geräten",
"92.htm	#§ 92 Notfallschutzgrundsätze",
"93.htm	#§ 93 Referenzwerte für den Schutz der Bevölkerung; Verordnungsermächtigungen",
"94.htm	#§ 94 Dosiswerte und Kontaminationswerte für den Schutz der Bevölkerung; Verordnungsermächtigungen",
"95.htm	#§ 95 Bewirtschaftung von Abfällen, die infolge eines Notfalls kontaminiert sein können, Errichtung und Betrieb von Anlagen; Verordnungsermächtigungen",
"95a.htm #§ 95a Auskunftsverlangen, Betretensrechte, Mitwirkungs- und Duldungspflichten",
"96.htm	#§ 96 Eilverordnungen",
"97.htm	#§ 97 Gemeinsame Vorschriften für die Notfallpläne",
"98.htm	#§ 98 Allgemeiner Notfallplan des Bundes",
"99.htm	#§ 99 Besondere Notfallpläne des Bundes",
"100.htm	#§ 100 Allgemeine und besondere Notfallpläne der Länder",
"101.htm	#§ 101 Externe Notfallpläne für ortsfeste Anlagen oder Einrichtungen mit besonderem Gefahrenpotential",
"102.htm	#§ 102 Notfallübungen",
"103.htm	#§ 103 Überprüfung und Änderung der Notfallpläne",
"104.htm	#§ 104 Beschaffung von Schutzwirkstoffen",
"105.htm	#§ 105 	Information der Bevölkerung über die Schutzmaßnahmen und Empfehlungen für das Verhalten bei möglichen Notfällen",
"106.htm	#§ 106 	Radiologisches Lagezentrum des Bundes",
"107.htm	#§ 107 Aufgaben der Länder bei der Ermittlung und Auswertung der radiologischen Lage",
"108.htm	#§ 108 Radiologisches Lagebild",
"109.htm	#§ 109 Entscheidungen über Schutzmaßnahmen durch die zuständigen Behörden",
"110.htm	#§ 110 Zusammenarbeit und Abstimmung bei Notfällen",
"111.htm	#§ 111 Dosisabschätzung, Abschätzung der Wirksamkeit der Schutzmaßnahmen, Anpassung der Notfallplanungen bei überregionalen und regionalen Notfällen",
"112.htm	#§ 112 Information der betroffenen Bevölkerung und Empfehlungen für das Verhalten bei Notfällen",
"113.htm	#§ 113 Unterrichtung, Aus- und Fortbildung der Einsatzkräfte im Rahmen der Notfallvorsorge",
"114.htm	#§ 114 Schutz der Einsatzkräfte bei Notfalleinsätzen",
"115.htm	#§ 115 Verantwortlichkeit für den Schutz der Einsatzkräfte",
"116.htm	#§ 116 Schutz der Einsatzkräfte bei anderen Gefahrenlagen",
"117.htm	#§ 117 Verordnungsermächtigungen zum Schutz der Einsatzkräfte",
"118.htm	#§ 118 Übergang zu einer bestehenden Expositionssituation; Verordnungsermächtigungen",
"119.htm	#§ 119 Radiologische Lage, Maßnahmen, Zusammenarbeit und Abstimmung in einer nach einem Notfall bestehenden Expositionssituation",
"120.htm	#§ 120 Information der Bevölkerung und Verhaltensempfehlungen",
"121.htm	#§ 121 Festlegung von Gebieten; Verordnungsermächtigung",
"122.htm	#§ 122 Radonmaßnahmenplan",
"123.htm	#§ 123 Maßnahmen an Gebäuden; Verordnungsermächtigung",
"124.htm	#§ 124 Referenzwert; Verordnungsermächtigung",
"125.htm	#§ 125 Unterrichtung der Bevölkerung; Reduzierung der Radonkonzentration",
"126.htm	#§ 126 Referenzwert",
"127.htm	#§ 127 Messung der Radonkonzentration",
"128.htm	#§ 128 Reduzierung der Radonkonzentration",
"129.htm	#§ 129 Anmeldung",
"130.htm	#§ 130 Abschätzung der Exposition",
"131.htm	#§ 131 Beruflicher Strahlenschutz",
"131a.htm	#§ 131a Aufgabe oder Änderung des angemeldeten Arbeitsplatzes",
"132.htm	#§ 132 Verordnungsermächtigung",
"133.htm	#§ 133 Referenzwert",
"134.htm	#§ 134 Bestimmung der spezifischen Aktivität",
"135.htm	#§ 135 Maßnahmen; Verordnungsermächtigung",
"136.htm	#§ 136 Begriff der radioaktiven Altlast; Verordnungsermächtigung",
"137.htm	#§ 137 Verantwortlichkeit für radioaktive Altlasten",
"138.htm	#§ 138 Verdacht auf radioaktive Altlasten",
"139.htm	#§ 139 Behördliche Anordnungsbefugnisse für Maßnahmen; Verordnungsermächtigung",
"140.htm	#§ 140 Weitere Pflichten im Zusammenhang mit der Durchführung von Maßnahmen",
"141.htm	#§ 141 Anwendung der Vorschriften für Tätigkeiten mit Rückständen",
"142.htm	#§ 142 Information der Öffentlichkeit; Erfassung",
"143.htm	#§ 143 Sanierungsplanung; Verordnungsermächtigung",
"144.htm	#§ 144 Behördliche Sanierungsplanung",
"145.htm	#§ 145 Schutz von Arbeitskräften; Verordnungsermächtigung",
"146.htm	#§ 146 Kosten; Ausgleichsanspruch",
"147.htm	#§ 147 Wertausgleich; Verordnungsermächtigung",
"148.htm	#§ 148 Sonstige bergbauliche und industrielle Hinterlassenschaften",
"149.htm	#§ 149 Stilllegung und Sanierung der Betriebsanlagen und Betriebsstätten des Uranerzbergbaus; Verordnungsermächtigung",
"150.htm	#§ 150 Verhältnis zu anderen Vorschriften",
"151.htm	#§ 151 Kontaminierte Gebiete in einer Notfallexpositionssituation; Verordnungsermächtigungen",
"152.htm	#§ 152 Kontaminierte Gebiete in einer nach einem Notfall bestehenden Expositionssituation; Verordnungsermächtigungen",
"153.htm	#§ 153 Verantwortlichkeit für sonstige bestehende Expositionssituationen",
"154.htm	#§ 154 Ermittlung und Bewertung einer sonstigen bestehenden Expositionssituation",
"155.htm	#§ 155 Verordnungsermächtigung für die Festlegung von Referenzwerten",
"156.htm	#§ 156 Maßnahmen",
"157.htm	#§ 157 Kosten; Ausgleichsanspruch",
"158.htm	#§ 158 Information",
"159.htm	#§ 159 Anmeldung; Anwendung der Bestimmungen zu geplanten Expositionssituationen; Verordnungsermächtigung",
"160.htm	#§ 160 Verhältnis zu den Kapiteln 1 bis 4",
"161.htm	#§ 161 Aufgaben des Bundes",
"162.htm	#§ 162 Aufgaben der Länder",
"163.htm	#§ 163 Integriertes Mess- und Informationssystem des Bundes",
"164.htm	#§ 164 Bewertung der Daten, Unterrichtung des Deutschen Bundestages und des Bundesrates",
"165.htm	#§ 165 Betretungsrecht und Probenahme",
"166.htm	#§ 166 Festlegungen zur Ermittlung der beruflichen Exposition",
"167.htm	#§ 167 Aufzeichnungs-, Aufbewahrungs- und behördliche Mitteilungspflichten für die ermittelte Körperdosis bei beruflicher Exposition",
"168.htm	#§ 168 Übermittlung der Ergebnisse der Ermittlung der Körperdosis",
"169.htm	#§ 169 Bestimmung von Messstellen; Verordnungsermächtigung",
"170.htm	#§ 170 Strahlenschutzregister; Verordnungsermächtigung",
"171.htm	#§ 171 Verordnungsermächtigung für Vorgaben in Bezug auf einen Strahlenpass",
"172.htm	#§ 172 Bestimmung von Sachverständigen; Verordnungsermächtigung",
"173.htm	#§ 173 Verordnungsermächtigungen für Mitteilungspflichten bei Fund und Erlangung",
"174.htm	#§ 174 Verordnungsermächtigung für behördliche Befugnisse bei kontaminiertem Metall",
"175.htm	#§ 175 Dosis- und Messgrößen; Verordnungsermächtigung",
"176.htm	#§ 176 Haftung für durch ionisierende Strahlung verursachte Schäden",
"177.htm	#§ 177 Vorsorge für die Erfüllung gesetzlicher Schadensersatzverpflichtungen",
"178.htm	#§ 178 Strahlenschutzrechtliche Aufsicht",
"179.htm	#§ 179 Anwendung des Atomgesetzes; Anordnungsbefugnis",
"180.htm	#§ 180 Aufsichtsprogramm; Verordnungsermächtigung",
"181.htm	#§ 181 Umweltverträglichkeitsprüfung",
"182.htm	#§ 182 Schriftform, elektronische Kommunikation",
"183.htm	#§ 183 Kosten; Verordnungsermächtigung",
"184.htm	#§ 184 Zuständigkeit der Landesbehörden",
"185.htm	#§ 185 Zuständigkeit des Bundesamtes für Strahlenschutz; Verordnungsermächtigung",
"186.htm	#§ 186 Zuständigkeit des Bundesamtes für die Sicherheit der nuklearen Entsorgung",
"187.htm	#§ 187 Zuständigkeit der Physikalisch-Technischen Bundesanstalt",
"188.htm	#§ 188 Zuständigkeiten für grenzüberschreitende Verbringungen und deren Überwachung",
"189.htm	#§ 189 Zuständigkeit des Luftfahrt-Bundesamtes",
"190.htm	#§ 190 Zuständigkeit des Eisenbahn-Bundesamtes",
"191.htm	#§ 191 Geschäftsbereich des Bundesministeriums der Verteidigung",
"192.htm	#§ 192 Zuständigkeiten von Verwaltungsbehörden des Bundes bei Aufgaben des Notfallschutzes und der Überwachung der Umweltradioaktivität; Verordnungsermächtigung",
"193.htm	#§ 193 Informationsübermittlung",
"193a.htm	#§ 193a Ausstattung der zuständigen Behörden",
"194.htm	#§ 194 Bußgeldvorschriften",
"195.htm	#§ 195 Einziehung",
"196.htm	#§ 196 Genehmigungsbedürftige Errichtung von Anlagen (§ 10)",
"197.htm	#§ 197 Genehmigungsbedürftige Tätigkeiten (§ 12)",
"198.htm	#§ 198 Genehmigungsbedürftiger Betrieb von Röntgeneinrichtungen und Störstrahlern (§ 12)",
"199.htm	#§ 199 Anzeigebedürftiger Betrieb von Anlagen (§ 17)",
"200.htm	#§ 200 	Anzeigebedürftiger Betrieb von Röntgeneinrichtungen und Störstrahlern (§ 19)",
"201.htm	#§ 201 	Anzeigebedürftige Prüfung, Erprobung, Wartung und Instandsetzung von Röntgeneinrichtungen und Störstrahlern (§ 22)",
"202.htm	#§ 202 	Genehmigungsbedürftige Beschäftigung in fremden Anlagen oder Einrichtungen (§ 25)",
"203.htm	#§ 203 	Anzeigebedürftige Beschäftigung im Zusammenhang mit dem Betrieb fremder Röntgeneinrichtungen und Störstrahler (§ 26)",
"204.htm	#§ 204 	Genehmigungsbedürftige Beförderung radioaktiver Stoffe (§ 27)",
"205.htm	#§ 205 	Medizinische Forschung (§§ 31, 32)",
"206.htm	#§ 206 	Genehmigungsbedürftiger Zusatz radioaktiver Stoffe und genehmigungsbedürftige Aktivierung (§ 40)",
"207.htm	#§ 207 	Genehmigungsbedürftige grenzüberschreitende Verbringung von Konsumgütern (§ 42)",
"208.htm	#§ 208 	Bauartzulassung (§ 45)",
"209.htm	#§ 209 	Anzeigebedürftiger Betrieb von Luftfahrzeugen (§ 50)",
"210.htm	#§ 210 	Anzeigebedürftige Tätigkeiten (§ 56)",
"211.htm	#§ 211 	Bestellung von Strahlenschutzbeauftragten (§ 70)",
"212.htm	#§ 212 	Grenzwerte für beruflich exponierte Personen; Ermittlung der Exposition der Bevölkerung (§§ 78, 80)",
"213.htm	#§ 213 	Zulassung der Früherkennung (§ 84)",
"214.htm	#§ 214 	Anmeldung von Arbeitsplätzen in Innenräumen (§ 129)",
"215.htm	#§ 215 	Radioaktive Altlasten",
"216.htm	#§ 216 	Bestimmung von Messstellen (§ 169)",
"217.htm	#§ 217 	Bestimmung von Sachverständigen (§ 172)",
"218.htm	#§ 218 	Genehmigungsfreier Umgang mit Geräten, keramischen Gegenständen, Porzellan- und Glaswaren oder elektronischen Bauteilen sowie sonstigen Produkten",
"anl1.htm	#Anlage 1 Rückstände nach § 5 Absatz 32",
"anl2.htm	#Anlage 2 Erforderliche Unterlagen zur Prüfung von Genehmigungsanträgen",
"anl3.htm	#Anlage 3 Tätigkeitsfelder nach § 55 Absatz 1",
"anl4.htm	#Anlage 4 Vorläufig als Notfallpläne des Bundes geltende Dokumente",
"anl5.htm	#Anlage 5 Wesentliche Elemente des allgemeinen Notfallplans des Bundes",
"anl6.htm	#Anlage 6 Wesentliche Elemente der besonderen Notfallpläne des Bundes",
"anl7.htm	#Anlage 7 Information der Bevölkerung und Empfehlungen für das Verhalten bei Notfällen",
"anl8.htm	#Anlage 8 Arbeitsfelder mit erhöhter Exposition durch Radon",
"anl9.htm	#Anlage 9 Radiologisch relevante mineralische Primärrohstoffe für die Herstellung von Gebäuden mit Aufenthaltsräumen"
);