ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"vor.htm	#Vorbemerkung",
"1.htm	#1 Anwendungsbereich",
"2.htm	#2 Begriffsbestimmungen",
"3.htm	#3 Grunds‰tzliches",
"4.htm	#4 Rettungssysteme",
"5.htm	#5 Gef‰hrdungsbeurteilung",
"6.htm	#6 Rettungskonzept",
"7.htm	#7 Beispiele Rettungsverfahren",
"8.htm	#8 Auswahl",
"9.htm	#9 Benutzung",
"10.htm	#10 Betriebsanweisung, Unterweisung",
"11.htm	#11 Ordnungsgem‰ﬂer Zustand",
"anh1.htm	#Anhang 1",
"anh2.htm	#Anhang 2",
"anh3.htm	#Anhang 3",
"anh4.htm	#Anhang 4",
"anh5.htm	#Anhang 5",
"anh6.htm	#Anhang 6"
);