ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Grundsatz",
"2.htm	#§ 2 Bestellung von Betriebsärzten",
"3.htm	#§ 3 Aufgaben der Betriebsärzte",
"4.htm	#§ 4 Anforderungen an Betriebsärzte",
"5.htm	#§ 5 Bestellung von Fachkräften für Arbeitssicherheit",
"6.htm	#§ 6 Aufgaben der Fachkräfte für Arbeitssicherheit",
"7.htm	#§ 7 Anforderungen an Fachkräfte für Arbeitssicherheit",
"8.htm	#§ 8 Unabhängigkeit bei der Anwendung der Fachkunde",
"9.htm	#§ 9 Zusammenarbeit mit dem Betriebsrat",
"10.htm	#§ 10 Zusammenarbeit der Betriebsärzte und der Fachkräfte",
"11.htm	#§ 11 Arbeitsschutzausschuß",
"12.htm	#§ 12 Behördliche Anordnungen",
"13.htm	#§ 13 Auskunfts-&nbsp;und Besichtigungsrechte",
"14.htm	#§ 14 Ermächtigung zum Erlaß von Rechtsverordnungen",
"15.htm	#§ 15 Ermächtigung zum Erlaß von allgemeinen Verwaltungsvorschriften",
"16.htm	#§ 16 Öffentliche Verwaltung",
"17.htm	#§ 17 Nichtanwendung des Gesetzes",
"18.htm	#§ 18 Ausnahmen",
"19.htm	#§ 19 Überbetriebliche Dienste",
"20.htm	#§ 20 Ordnungswidrigkeiten",
"21.htm	#§ 21 Änderung der Reichsversicherungsordnung",
"22.htm	#§ 22 Berlin-Klausel",
"23.htm	#§ 23 Inkrafttreten"
);