ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Geltungsbereich",
"1a.htm	#§ 1a Formvorgaben",
"2.htm	#§ 2 Kind, Jugendlicher",
"3.htm	#§ 3 Arbeitgeber",
"4.htm	#§ 4 Arbeitszeit",
"5.htm	#§ 5 Verbot der Beschäftigung von Kindern",
"6.htm	#§ 6 Behördliche Ausnahmen für Veranstaltungen",
"7.htm	#§ 7 Beschäftigung von nicht vollzeitschulpflichtigen Kindern",
"8.htm	#§ 8 Dauer der Arbeitszeit",
"9.htm	#§ 9 Berufsschule",
"10.htm	#§ 10 Prüfungen und außerbetriebliche Ausbildungsmaßnahmen",
"11.htm	#§ 11 Ruhepausen, Aufenthaltsräume",
"12.htm	#§ 12 Schichtzeit",
"13.htm	#§ 13 Tägliche Freizeit",
"14.htm	#§ 14 Nachtruhe",
"15.htm	#§ 15 Fünf-Tage-Woche",
"16.htm	#§ 16 Samstagsruhe",
"17.htm	#§ 17 Sonntagsruhe",
"18.htm	#§ 18 Feiertagsruhe",
"19.htm	#§ 19 Urlaub",
"20.htm	#§ 20 Binnenschiffahrt",
"21.htm	#§ 21 Ausnahmen in besonderen Fällen",
"21a.htm	#§ 21 a Abweichende Regelungen",
"21b.htm	#§ 21 b Ermächtigung",
"22.htm	#§ 22 Gefährliche Arbeiten",
"23.htm	#§ 23 Akkordarbeit;&nbsp;tempoabhängige Arbeiten",
"24.htm	#§ 24 Arbeiten unter Tage",
"25.htm	#§ 25 Verbot der Beschäftigung durch bestimmte Personen",
"26.htm	#§ 26 Ermächtigungen",
"27.htm	#§ 27 Behördliche Anordnungen und Ausnahmen",
"28.htm	#§ 28 Menschengerechte Gestaltung der Arbeit",
"28a.htm	#§ 28 a Beurteilung der Arbeitsbedingungen",
"29.htm	#§ 29 Unterweisung über Gefahren",
"30.htm	#§ 30 Häusliche Gemeinschaft",
"31.htm	#§ 31 Züchtigungsverbot;&nbsp;Verbot der Abgabe von Alkohol und Tabak",
"32.htm	#§ 32 Erstuntersuchung",
"33.htm	#§ 33 Erste Nachuntersuchung",
"34.htm	#§ 34 Weitere Nachuntersuchungen",
"35.htm	#§ 35 Außerordentliche Nachuntersuchung",
"36.htm	#§ 36 Ärztliche Untersuchungen und Wechsel des Arbeitgebers",
"37.htm	#§ 37 Inhalt und Durchführung der ärztlichen Untersuchungen",
"38.htm	#§ 38 Ergänzungsuntersuchung",
"39.htm	#§ 39 Mitteilung, Bescheinigung",
"40.htm	#§ 40 Bescheinigung mit Gefährdungsvermerk",
"41.htm	#§ 41 Aufbewahren der ärztlichen Bescheinigungen",
"42.htm	#§ 42 Eingreifen der Aufsichtsbehörde",
"43.htm	#§ 43 Freistellung für Untersuchungen",
"44.htm	#§ 44 Kosten der Untersuchungen",
"45.htm	#§ 45 Gegenseitige Unterrichtung der Ärzte",
"46.htm	#§ 46 Ermächtigungen",
"47.htm	#§ 47 Bekanntgabe des Gesetzes und der Aufsichtsbehörde",
"48.htm	#§ 48 Information über Arbeitszeit und Pausen",
"49.htm	#§ 49 Verzeichnisse der Jugendlichen",
"50.htm	#§ 50 Auskunft;&nbsp;Vorlage der Verzeichnisse",
"51.htm	#§ 51 Aufsichtsbehörde; Besichtigungsrechte und Berichtspflicht",
"52.htm	#§ 52 (weggefallen)",
"53.htm	#§ 53 Mitteilung über Verstöße",
"54.htm	#§ 54 Ausnahmebewilligung",
"55.htm	#§ 55 Bildung des Landesausschusses für Jugendarbeitsschutz",
"56.htm	#§ 56 Bildung des Ausschusses für Jugendarbeitsschutz bei der Aufsichtsbehörde",
"57.htm	#§ 57 Aufgaben der Ausschüsse",
"58.htm	#§ 58 Bußgeld-&nbsp;und Strafvorschriften",
"59.htm	#§ 59 Bußgeldvorschriften",
"60.htm	#§ 60 Verwaltungsvorschriften für die Verfolgung und Ahndung von Ordnungswidrigkeiten",
"61.htm	#§ 61 Beschäftigung von Jugendlichen auf Kauffahrteischiffen",
"62.htm	#§ 62 Beschäftigung im Vollzug einer Freiheitsentziehung",
"63.htm	#§§ 63-70 (Änderungsvorschriften)",
"71.htm	#§ 71 (weggefallen)",
"72.htm	#§ 72 Inkrafttreten"
);