ord=new Array(
"titel.htm	#Titel",
"inhalt.htm	#Inhaltsübersicht",
"1.htm	#§ 1 Anwendungsbereich",
"2.htm	#§ 2 Begriffsbestimmungen",
"3.htm	#§ 3 Allgemeine Anforderungen an die Bereitstellung von Produkten auf dem Markt",
"4.htm	#§ 4 Harmonisierte Normen",
"5.htm	#§ 5 Normen und andere technische Spezifikationen",
"6.htm	#§ 6 Zusätzliche Anforderungen an die Bereitstellung von Verbraucherprodukten auf dem Markt",
"7.htm	#§ 7 CE-Kennzeichnung",
"8.htm	#§ 8 Ermächtigung zum Erlass von Rechtsverordnungen",
"9.htm	#§ 9 Aufgaben der Befugnis erteilenden Behörde",
"10.htm	#§ 10 Anforderungen an die Befugnis erteilende Behörde",
"11.htm	#§ 11 Befugnisse der Befugnis erteilenden Behörde",
"12.htm	#§ 12 Anträge auf Notifizierung",
"13.htm	#§ 13 Anforderungen an die Konformitätsbewertungsstelle für ihre Notifizierung",
"14.htm	#§ 14 Konformitätsvermutung",
"15.htm	#§ 15 Erteilung der Befugnis, Notifizierungsverfahren",
"16.htm	#§ 16 Verpflichtungen der notifizierten Stelle",
"17.htm	#§ 17 Meldepflichten der notifizierten Stelle",
"18.htm	#§ 18 Zweigunternehmen einer notifizierten Stelle und Vergabe von Unteraufträgen",
"19.htm	#§ 19 Widerruf der erteilten Befugnis",
"20.htm	#§ 20 Zuerkennung des GS-Zeichens",
"21.htm	#§ 21 Befugnis für die Tätigkeit als GS-Stelle",
"22.htm	#§ 22 Pflichten der GS-Stellen",
"23.htm	#§ 23 Einbeziehung von externen Stellen",
"24.htm	#§ 24 Pflichten des Herstellers und des Einführers",
"25.htm	#§ 25 Marktüberwachung",
"26.htm	#§ 26 Aufgaben der Bundesanstalt für Arbeitsschutz und Arbeitsmedizin",
"27.htm	#§ 27 Ausschuss für Produktsicherheit",
"28.htm	#§ 28 Bußgeldvorschriften",
"29.htm	#§ 29 Strafvorschriften",
"anl.htm	#Anlage Gestaltung des GS-Zeichens"
);