ord=new Array(
"titel.htm	#Titelseite",
"inhalt.htm	#Inhalt",
"1.htm	#§ 1 Zweck des Gesetzes",
"2.htm	#§ 2 Anwendungsbereich",
"3.htm	#§ 3 Begriffsbestimmungen",
"3a.htm	#§ 3a Gefährliche Stoffe und gefährliche Gemische",
"3b.htm	#§ 3b (weggefallen)",
"4.htm	#§ 4 Beteiligte Bundesbehörden",
"5.htm	#§ 5 Aufgaben der Bundesstelle für Chemikalien",
"6.htm	#§ 6 Aufgaben der Bewertungsstellen",
"7.htm	#§ 7 Zusammenarbeit der Bundesstelle für Chemikalien und der anderen beteiligten Bundesoberbehörden",
"8.htm	#§ 8 Gebührenfreiheit der nationalen Auskunftsstelle",
"9.htm	#§ 9 Informationsaustausch zwischen Bundes- und Landesbehörden",
"10.htm	#§ 10 Vorläufige Maßnahmen",
"11.htm	#§ 11 weggefallen",
"12.htm	#§ 12 weggefallen",
"12a.htm	#§ 12a Beteiligte Bundesbehörden",
"12b.htm	#§ 12b Aufgaben der Bundesstelle für Chemikalien",
"12c.htm	#§ 12c Aufgaben der Bewertungsstellen",
"12d.htm	#§ 12d Zusammenarbeit der Bundesstelle für Chemikalien und der anderen beteiligten Bundesoberbehörden",
"12e.htm	#§ 12e Auskunftsstelle, Unterrichtung der Öffentlichkeit",
"12f.htm	#§ 12f Informationsaustausch zwischen Bundes- und Landesbehörden",
"12g.htm	#§ 12g Anordnungsbefugnisse der Bundesstelle für Chemikalien, vorläufige Maßnahmen",
"12h.htm	#§ 12h Verordnungsermächtigungen",
"12i.htm	#§ 12i Ergänzende Pflichten zu Kapitel III der Verordnung (EU) Nr. 517/2014",
"12j.htm	#§ 12j Ergänzende Pflichten zu Kapitel IV der Verordnung (EU) Nr. 517/2014",
"12k.htm	#§ 12k Verordnungsermächtigungen",
"13.htm	#§ 13 Einstufungs-, Kennzeichnungs- und Verpackungspflichten",
"14.htm	#§ 14 Ermächtigung zu Einstufungs-, Kennzeichnungs- und Verpackungsvorschriften",
"15.htm	#§ 15 (weggefallen)",
"15a.htm	#§ 15a (weggefallen)",
"16.htm	#§ 16 weggefallen",
"16a.htm	#§ 16a weggefallen",
"16b.htm	#§ 16b weggefallen",
"16c.htm	#§ 16c weggefallen",
"16d.htm	#§ 16d Mitteilungspflichten bei Gemischen",
"16e.htm	#§ 16e Mitteilungen für die gesundheitliche Notversorgung und für vorbeugende Maßnahmen",
"16f.htm	#§ 16f Informationspflicht der Lieferanten",
"17.htm	#§ 17 Verbote und Beschränkungen",
"18.htm	#§ 18 Giftige Tiere und Pflanzen",
"19.htm	#§ 19 Maßnahmen zum Schutz von Beschäftigten",
"19a.htm	#§ 19a Gute Laborpraxis (GLP)",
"19b.htm	#§ 19b, GLP-Bescheinigung",
"19c.htm	#§ 19c Berichterstattung",
"19d.htm	#§ 19d Ergänzende Vorschriften",
"20.htm	#§ 20 Antrags- und Mitteilungsunterlagen, Verordnungsermächtigungen",
"20a.htm	#§ 20a (weggefallen)",
"20b.htm	#§ 20b Ausschüsse",
"21.htm	#§ 21 Überwachung",
"21a.htm	#§ 21a Mitwirkung von Zollstellen",
"22.htm	#§ 22 Informationspflichten",
"23.htm	#§ 23 Behördliche Anordnungen",
"24.htm	#§ 24 Vollzug im Bereich der Bundeswehr",
"25.htm	#§ 25 Angleichung an Gemeinschaftsrecht oder Unionsrecht",
"25a.htm	#§ 25a Aufwendungen des Auskunftspflichtigen",
"26.htm	#§ 26 Bußgeldvorschriften, Verordnungsermächtigung",
"27.htm	#§ 27 Strafvorschriften, Verordnungsermächtigung",
"27a.htm	#§ 27a Unwahre GLP-Erklärungen, Erschleichen der GLP-Bescheinigung",
"27b.htm	#§ 27b Zuwiderhandlungen gegen die Verordnung (EG) Nr. 1907/2006",
"27c.htm	#§ 27c Zuwiderhandlungen gegen Abgabevorschriften",
"27d.htm	#§ 27d Einziehung",
"28.htm	#§ 28 Übergangsregelung",
"29.htm	#§ 29 Außerkrafttreten",
"30.htm	#§ 30 Berlin-Klausel",
"31.htm	#§ 31 Inkrafttreten",
"anh1.htm	#Anhang 1 (GLP): Inhaltsübersicht",
"a1_1.htm	#Anhang 1 (GLP): Abschnitt I, 1 Anwendungsbereich",
"a1_2.htm	#Anhang 1 (GLP): Abschnitt I, 2 Begriffsbestimmungen",
"a2_1.htm	#Anhang 1 (GLP): Abschnitt II&nbsp;1 Organisation und Personal der Prüfeinrichtung",
"a2_2.htm	#Anhang 1 (GLP): Abschnitt II&nbsp;2 Qualitätssicherungsprogramm",
"a2_3.htm	#Anhang 1 (GLP): Abschnitt II&nbsp;3 Räumlichkeiten und Einrichtungen",
"a2_4.htm	#Anhang 1 (GLP): Abschnitt II&nbsp;4 Geräte, Materialien und Reagenzien",
"a2_5.htm	#Anhang 1 (GLP): Abschnitt II&nbsp;5 Prüfsysteme",
"a2_6.htm	#Anhang 1 (GLP): Abschnitt II&nbsp;6 Prüf- und Referenzgegenstände",
"a2_7.htm	#Anhang 1 (GLP): Abschnitt II&nbsp;7 Standardarbeitsanweisungen (Standard Operating Procedures, SOPs)",
"a2_8.htm	#Anhang 1 (GLP): Abschnitt II&nbsp;8 Prüfungsablauf",
"a2_9.htm	#Anhang 1 (GLP): Abschnitt II&nbsp;9 Bericht über die Prüfergebnisse",
"a2_10.htm	#Anhang 1 (GLP): Abschnitt II&nbsp;10 Archivierung und Aufbewahrung von Aufzeichnungen und Materialien",
"anh2.htm	#Anhang 2: GLP-Bescheinigung"
);